// Code generated by protoc-gen-go. DO NOT EDIT.
// source: C2G.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type C2G_UserLogin_LoginType int32

const (
	C2G_UserLogin_Device C2G_UserLogin_LoginType = 0
	C2G_UserLogin_QQ     C2G_UserLogin_LoginType = 1
	C2G_UserLogin_WeiXin C2G_UserLogin_LoginType = 2
	C2G_UserLogin_Email  C2G_UserLogin_LoginType = 3
	C2G_UserLogin_Phone  C2G_UserLogin_LoginType = 4
)

var C2G_UserLogin_LoginType_name = map[int32]string{
	0: "Device",
	1: "QQ",
	2: "WeiXin",
	3: "Email",
	4: "Phone",
}
var C2G_UserLogin_LoginType_value = map[string]int32{
	"Device": 0,
	"QQ":     1,
	"WeiXin": 2,
	"Email":  3,
	"Phone":  4,
}

func (x C2G_UserLogin_LoginType) String() string {
	return proto.EnumName(C2G_UserLogin_LoginType_name, int32(x))
}
func (C2G_UserLogin_LoginType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_C2G_013ac8ace367eed0, []int{0, 0}
}

// 玩家登录游戏服务器
type C2G_UserLogin struct {
	LoginType            C2G_UserLogin_LoginType `protobuf:"varint,4,opt,name=loginType,proto3,enum=message.C2G_UserLogin_LoginType" json:"loginType,omitempty"`
	GameServerId         int32                   `protobuf:"varint,1,opt,name=gameServerId,proto3" json:"gameServerId,omitempty"`
	UserName             string                  `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	Password             string                  `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *C2G_UserLogin) Reset()         { *m = C2G_UserLogin{} }
func (m *C2G_UserLogin) String() string { return proto.CompactTextString(m) }
func (*C2G_UserLogin) ProtoMessage()    {}
func (*C2G_UserLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2G_013ac8ace367eed0, []int{0}
}
func (m *C2G_UserLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2G_UserLogin.Unmarshal(m, b)
}
func (m *C2G_UserLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2G_UserLogin.Marshal(b, m, deterministic)
}
func (dst *C2G_UserLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2G_UserLogin.Merge(dst, src)
}
func (m *C2G_UserLogin) XXX_Size() int {
	return xxx_messageInfo_C2G_UserLogin.Size(m)
}
func (m *C2G_UserLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_C2G_UserLogin.DiscardUnknown(m)
}

var xxx_messageInfo_C2G_UserLogin proto.InternalMessageInfo

func (m *C2G_UserLogin) GetLoginType() C2G_UserLogin_LoginType {
	if m != nil {
		return m.LoginType
	}
	return C2G_UserLogin_Device
}

func (m *C2G_UserLogin) GetGameServerId() int32 {
	if m != nil {
		return m.GameServerId
	}
	return 0
}

func (m *C2G_UserLogin) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *C2G_UserLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 玩家选择该角色登录
type C2G_SelectCharacter struct {
	RoleId               int64    `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2G_SelectCharacter) Reset()         { *m = C2G_SelectCharacter{} }
func (m *C2G_SelectCharacter) String() string { return proto.CompactTextString(m) }
func (*C2G_SelectCharacter) ProtoMessage()    {}
func (*C2G_SelectCharacter) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2G_013ac8ace367eed0, []int{1}
}
func (m *C2G_SelectCharacter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2G_SelectCharacter.Unmarshal(m, b)
}
func (m *C2G_SelectCharacter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2G_SelectCharacter.Marshal(b, m, deterministic)
}
func (dst *C2G_SelectCharacter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2G_SelectCharacter.Merge(dst, src)
}
func (m *C2G_SelectCharacter) XXX_Size() int {
	return xxx_messageInfo_C2G_SelectCharacter.Size(m)
}
func (m *C2G_SelectCharacter) XXX_DiscardUnknown() {
	xxx_messageInfo_C2G_SelectCharacter.DiscardUnknown(m)
}

var xxx_messageInfo_C2G_SelectCharacter proto.InternalMessageInfo

func (m *C2G_SelectCharacter) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

// 玩家创建该角色
type C2G_CreateCharacter struct {
	NickName             string   `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
	AvatarId             int32    `protobuf:"varint,2,opt,name=avatarId,proto3" json:"avatarId,omitempty"`
	Sex                  int32    `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2G_CreateCharacter) Reset()         { *m = C2G_CreateCharacter{} }
func (m *C2G_CreateCharacter) String() string { return proto.CompactTextString(m) }
func (*C2G_CreateCharacter) ProtoMessage()    {}
func (*C2G_CreateCharacter) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2G_013ac8ace367eed0, []int{2}
}
func (m *C2G_CreateCharacter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2G_CreateCharacter.Unmarshal(m, b)
}
func (m *C2G_CreateCharacter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2G_CreateCharacter.Marshal(b, m, deterministic)
}
func (dst *C2G_CreateCharacter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2G_CreateCharacter.Merge(dst, src)
}
func (m *C2G_CreateCharacter) XXX_Size() int {
	return xxx_messageInfo_C2G_CreateCharacter.Size(m)
}
func (m *C2G_CreateCharacter) XXX_DiscardUnknown() {
	xxx_messageInfo_C2G_CreateCharacter.DiscardUnknown(m)
}

var xxx_messageInfo_C2G_CreateCharacter proto.InternalMessageInfo

func (m *C2G_CreateCharacter) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *C2G_CreateCharacter) GetAvatarId() int32 {
	if m != nil {
		return m.AvatarId
	}
	return 0
}

func (m *C2G_CreateCharacter) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func init() {
	proto.RegisterType((*C2G_UserLogin)(nil), "message.C2G_UserLogin")
	proto.RegisterType((*C2G_SelectCharacter)(nil), "message.C2G_SelectCharacter")
	proto.RegisterType((*C2G_CreateCharacter)(nil), "message.C2G_CreateCharacter")
	proto.RegisterEnum("message.C2G_UserLogin_LoginType", C2G_UserLogin_LoginType_name, C2G_UserLogin_LoginType_value)
}

func init() { proto.RegisterFile("C2G.proto", fileDescriptor_C2G_013ac8ace367eed0) }

var fileDescriptor_C2G_013ac8ace367eed0 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xdd, 0xa4, 0x8d, 0xcd, 0xa0, 0xb2, 0xac, 0x20, 0xa1, 0xa7, 0x90, 0x53, 0x2f, 0xe6,
	0x10, 0xef, 0x82, 0x44, 0x29, 0x42, 0x11, 0x9b, 0x2a, 0x7a, 0x2b, 0x6b, 0x3a, 0xa4, 0x8b, 0x49,
	0x36, 0xec, 0xc6, 0xa8, 0x5f, 0xda, 0xcf, 0x20, 0x9b, 0x7f, 0xa5, 0xb7, 0xf7, 0xe6, 0xbd, 0x65,
	0xe7, 0xc7, 0x80, 0x1b, 0x47, 0xcb, 0xb0, 0x52, 0xb2, 0x96, 0xec, 0xb4, 0x40, 0xad, 0x79, 0x86,
	0xc1, 0x1f, 0x81, 0xf3, 0x38, 0x5a, 0x6e, 0x5f, 0x35, 0xaa, 0x95, 0xcc, 0x44, 0xc9, 0x6e, 0xc1,
	0xcd, 0x8d, 0x78, 0xf9, 0xad, 0xd0, 0x9b, 0xf8, 0x64, 0x71, 0x11, 0xf9, 0x61, 0x5f, 0x0f, 0x8f,
	0xaa, 0xe1, 0x6a, 0xe8, 0x25, 0x87, 0x27, 0x2c, 0x80, 0xb3, 0x8c, 0x17, 0xb8, 0x41, 0xd5, 0xa0,
	0x7a, 0xdc, 0x79, 0xc4, 0x27, 0x8b, 0x69, 0x72, 0x34, 0x63, 0x73, 0x98, 0x7d, 0x69, 0x54, 0x4f,
	0xbc, 0x40, 0xcf, 0xf2, 0xc9, 0xc2, 0x4d, 0x46, 0x6f, 0xb2, 0x8a, 0x6b, 0xfd, 0x2d, 0xd5, 0xce,
	0xb3, 0xbb, 0x6c, 0xf0, 0xc1, 0x1d, 0xb8, 0xe3, 0x9f, 0x0c, 0xc0, 0xb9, 0xc7, 0x46, 0xa4, 0x48,
	0x4f, 0x98, 0x03, 0xd6, 0x7a, 0x4d, 0x89, 0x99, 0xbd, 0xa1, 0x78, 0x17, 0x25, 0xb5, 0x98, 0x0b,
	0xd3, 0x87, 0x82, 0x8b, 0x9c, 0xda, 0x46, 0x3e, 0xef, 0x65, 0x89, 0x74, 0x12, 0x5c, 0xc3, 0xa5,
	0x81, 0xd8, 0x60, 0x8e, 0x69, 0x1d, 0xef, 0xb9, 0xe2, 0x69, 0x8d, 0x8a, 0x5d, 0x81, 0xa3, 0x64,
	0x8e, 0xfd, 0xbe, 0x76, 0xd2, 0xbb, 0x60, 0xdb, 0xd5, 0x63, 0x85, 0xbc, 0xc6, 0x43, 0x7d, 0x0e,
	0xb3, 0x52, 0xa4, 0x9f, 0x2d, 0x00, 0xe9, 0x96, 0x1c, 0xbc, 0xc9, 0x78, 0xc3, 0x6b, 0x6e, 0xe0,
	0xad, 0x16, 0x7e, 0xf4, 0x8c, 0x82, 0xad, 0xf1, 0xa7, 0xe5, 0x9a, 0x26, 0x46, 0x7e, 0x38, 0xed,
	0x41, 0x6e, 0xfe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x51, 0xab, 0x3c, 0x9d, 0x01, 0x00, 0x00,
}
