// Code generated by protoc-gen-go. DO NOT EDIT.
// source: C2G.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 玩家登录游戏服务器
type C2G_UserLogin struct {
	GameServerId         int32    `protobuf:"varint,1,opt,name=gameServerId,proto3" json:"gameServerId,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2G_UserLogin) Reset()         { *m = C2G_UserLogin{} }
func (m *C2G_UserLogin) String() string { return proto.CompactTextString(m) }
func (*C2G_UserLogin) ProtoMessage()    {}
func (*C2G_UserLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2G_024838d5056654c4, []int{0}
}
func (m *C2G_UserLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2G_UserLogin.Unmarshal(m, b)
}
func (m *C2G_UserLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2G_UserLogin.Marshal(b, m, deterministic)
}
func (dst *C2G_UserLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2G_UserLogin.Merge(dst, src)
}
func (m *C2G_UserLogin) XXX_Size() int {
	return xxx_messageInfo_C2G_UserLogin.Size(m)
}
func (m *C2G_UserLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_C2G_UserLogin.DiscardUnknown(m)
}

var xxx_messageInfo_C2G_UserLogin proto.InternalMessageInfo

func (m *C2G_UserLogin) GetGameServerId() int32 {
	if m != nil {
		return m.GameServerId
	}
	return 0
}

func (m *C2G_UserLogin) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *C2G_UserLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// 玩家选择该角色登录
type C2G_SelectCharacter struct {
	RoleId               int64    `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2G_SelectCharacter) Reset()         { *m = C2G_SelectCharacter{} }
func (m *C2G_SelectCharacter) String() string { return proto.CompactTextString(m) }
func (*C2G_SelectCharacter) ProtoMessage()    {}
func (*C2G_SelectCharacter) Descriptor() ([]byte, []int) {
	return fileDescriptor_C2G_024838d5056654c4, []int{1}
}
func (m *C2G_SelectCharacter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2G_SelectCharacter.Unmarshal(m, b)
}
func (m *C2G_SelectCharacter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2G_SelectCharacter.Marshal(b, m, deterministic)
}
func (dst *C2G_SelectCharacter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2G_SelectCharacter.Merge(dst, src)
}
func (m *C2G_SelectCharacter) XXX_Size() int {
	return xxx_messageInfo_C2G_SelectCharacter.Size(m)
}
func (m *C2G_SelectCharacter) XXX_DiscardUnknown() {
	xxx_messageInfo_C2G_SelectCharacter.DiscardUnknown(m)
}

var xxx_messageInfo_C2G_SelectCharacter proto.InternalMessageInfo

func (m *C2G_SelectCharacter) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func init() {
	proto.RegisterType((*C2G_UserLogin)(nil), "message.C2G_UserLogin")
	proto.RegisterType((*C2G_SelectCharacter)(nil), "message.C2G_SelectCharacter")
}

func init() { proto.RegisterFile("C2G.proto", fileDescriptor_C2G_024838d5056654c4) }

var fileDescriptor_C2G_024838d5056654c4 = []byte{
	// 163 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x74, 0x36, 0x72, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55, 0xca,
	0xe6, 0xe2, 0x75, 0x36, 0x72, 0x8f, 0x0f, 0x2d, 0x4e, 0x2d, 0xf2, 0xc9, 0x4f, 0xcf, 0xcc, 0x13,
	0x52, 0xe2, 0xe2, 0x49, 0x4f, 0xcc, 0x4d, 0x0d, 0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xf2, 0x4c, 0x91,
	0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x42, 0x11, 0x13, 0x92, 0xe2, 0xe2, 0x28, 0x2d, 0x4e, 0x2d,
	0xf2, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x41, 0x72, 0x05,
	0x89, 0xc5, 0xc5, 0xe5, 0xf9, 0x45, 0x29, 0x12, 0xcc, 0x10, 0x39, 0x18, 0x5f, 0x49, 0x97, 0x4b,
	0x18, 0x64, 0x59, 0x70, 0x6a, 0x4e, 0x6a, 0x72, 0x89, 0x73, 0x46, 0x62, 0x51, 0x62, 0x72, 0x49,
	0x6a, 0x91, 0x90, 0x18, 0x17, 0x5b, 0x51, 0x7e, 0x4e, 0x2a, 0xd4, 0x32, 0xe6, 0x20, 0x28, 0x2f,
	0x89, 0x0d, 0xec, 0x56, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x08, 0xc4, 0x2d, 0x30, 0xb8,
	0x00, 0x00, 0x00,
}
