// Code generated by protoc-gen-go. DO NOT EDIT.
// source: G2C.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type G2C_CharacterInfo struct {
	Role                 *Role    `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *G2C_CharacterInfo) Reset()         { *m = G2C_CharacterInfo{} }
func (m *G2C_CharacterInfo) String() string { return proto.CompactTextString(m) }
func (*G2C_CharacterInfo) ProtoMessage()    {}
func (*G2C_CharacterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_G2C_de9178c7e6f63504, []int{0}
}
func (m *G2C_CharacterInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_G2C_CharacterInfo.Unmarshal(m, b)
}
func (m *G2C_CharacterInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_G2C_CharacterInfo.Marshal(b, m, deterministic)
}
func (dst *G2C_CharacterInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_G2C_CharacterInfo.Merge(dst, src)
}
func (m *G2C_CharacterInfo) XXX_Size() int {
	return xxx_messageInfo_G2C_CharacterInfo.Size(m)
}
func (m *G2C_CharacterInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_G2C_CharacterInfo.DiscardUnknown(m)
}

var xxx_messageInfo_G2C_CharacterInfo proto.InternalMessageInfo

func (m *G2C_CharacterInfo) GetRole() *Role {
	if m != nil {
		return m.Role
	}
	return nil
}

type Role struct {
	RoleId               int64    `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	AvatarId             int32    `protobuf:"varint,3,opt,name=avatarId,proto3" json:"avatarId,omitempty"`
	Level                int32    `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Exp                  int32    `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	Gold                 int32    `protobuf:"varint,6,opt,name=gold,proto3" json:"gold,omitempty"`
	Diam                 int32    `protobuf:"varint,7,opt,name=diam,proto3" json:"diam,omitempty"`
	MaxBagNum            int32    `protobuf:"varint,8,opt,name=maxBagNum,proto3" json:"maxBagNum,omitempty"`
	RankScore            int32    `protobuf:"varint,9,opt,name=rankScore,proto3" json:"rankScore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Role) Reset()         { *m = Role{} }
func (m *Role) String() string { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()    {}
func (*Role) Descriptor() ([]byte, []int) {
	return fileDescriptor_G2C_de9178c7e6f63504, []int{1}
}
func (m *Role) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Role.Unmarshal(m, b)
}
func (m *Role) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Role.Marshal(b, m, deterministic)
}
func (dst *Role) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Role.Merge(dst, src)
}
func (m *Role) XXX_Size() int {
	return xxx_messageInfo_Role.Size(m)
}
func (m *Role) XXX_DiscardUnknown() {
	xxx_messageInfo_Role.DiscardUnknown(m)
}

var xxx_messageInfo_Role proto.InternalMessageInfo

func (m *Role) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *Role) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *Role) GetAvatarId() int32 {
	if m != nil {
		return m.AvatarId
	}
	return 0
}

func (m *Role) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Role) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *Role) GetGold() int32 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *Role) GetDiam() int32 {
	if m != nil {
		return m.Diam
	}
	return 0
}

func (m *Role) GetMaxBagNum() int32 {
	if m != nil {
		return m.MaxBagNum
	}
	return 0
}

func (m *Role) GetRankScore() int32 {
	if m != nil {
		return m.RankScore
	}
	return 0
}

// 强制客户端退出游戏
type G2C_QuitGame struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *G2C_QuitGame) Reset()         { *m = G2C_QuitGame{} }
func (m *G2C_QuitGame) String() string { return proto.CompactTextString(m) }
func (*G2C_QuitGame) ProtoMessage()    {}
func (*G2C_QuitGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_G2C_de9178c7e6f63504, []int{2}
}
func (m *G2C_QuitGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_G2C_QuitGame.Unmarshal(m, b)
}
func (m *G2C_QuitGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_G2C_QuitGame.Marshal(b, m, deterministic)
}
func (dst *G2C_QuitGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_G2C_QuitGame.Merge(dst, src)
}
func (m *G2C_QuitGame) XXX_Size() int {
	return xxx_messageInfo_G2C_QuitGame.Size(m)
}
func (m *G2C_QuitGame) XXX_DiscardUnknown() {
	xxx_messageInfo_G2C_QuitGame.DiscardUnknown(m)
}

var xxx_messageInfo_G2C_QuitGame proto.InternalMessageInfo

func init() {
	proto.RegisterType((*G2C_CharacterInfo)(nil), "message.G2C_CharacterInfo")
	proto.RegisterType((*Role)(nil), "message.Role")
	proto.RegisterType((*G2C_QuitGame)(nil), "message.G2C_QuitGame")
}

func init() { proto.RegisterFile("G2C.proto", fileDescriptor_G2C_de9178c7e6f63504) }

var fileDescriptor_G2C_de9178c7e6f63504 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x46, 0x65, 0xf2, 0xd3, 0x66, 0xf8, 0x11, 0x58, 0x08, 0x59, 0x88, 0x45, 0xc8, 0x2a, 0xab,
	0x2c, 0x82, 0xc4, 0x01, 0xc8, 0x22, 0xca, 0xa6, 0x12, 0xe6, 0x00, 0x68, 0x48, 0x86, 0x10, 0xd5,
	0x8e, 0x2b, 0x37, 0xad, 0x7a, 0x5e, 0x4e, 0x82, 0xec, 0x54, 0x61, 0xf7, 0xbd, 0xf7, 0x66, 0x35,
	0x90, 0xd4, 0x65, 0x55, 0xec, 0xac, 0x99, 0x0c, 0x5f, 0x69, 0xda, 0xef, 0xb1, 0xa7, 0xec, 0x15,
	0xee, 0xea, 0xb2, 0xfa, 0xac, 0x7e, 0xd0, 0x62, 0x3b, 0x91, 0x6d, 0xc6, 0x6f, 0xc3, 0x9f, 0x21,
	0xb4, 0x46, 0x91, 0x60, 0x29, 0xcb, 0x2f, 0xcb, 0xeb, 0xe2, 0x7c, 0x5c, 0x48, 0xa3, 0x48, 0xfa,
	0x94, 0xfd, 0x32, 0x08, 0x1d, 0xf2, 0x07, 0x88, 0x9d, 0x68, 0x3a, 0x7f, 0x1d, 0xc8, 0x33, 0xf1,
	0x47, 0x58, 0x8f, 0x43, 0xbb, 0xdd, 0xa0, 0x26, 0x71, 0x91, 0xb2, 0x3c, 0x91, 0x0b, 0xbb, 0x86,
	0x47, 0x9c, 0xd0, 0x36, 0x9d, 0x08, 0x52, 0x96, 0x47, 0x72, 0x61, 0x7e, 0x0f, 0x91, 0xa2, 0x23,
	0x29, 0x11, 0xfa, 0x30, 0x03, 0xbf, 0x85, 0x80, 0x4e, 0x3b, 0x11, 0x79, 0xe7, 0x26, 0xe7, 0x10,
	0xf6, 0x46, 0x75, 0x22, 0xf6, 0xca, 0x6f, 0xe7, 0xba, 0x01, 0xb5, 0x58, 0xcd, 0xce, 0x6d, 0xfe,
	0x04, 0x89, 0xc6, 0xd3, 0x1b, 0xf6, 0x9b, 0x83, 0x16, 0x6b, 0x1f, 0xfe, 0x85, 0xab, 0x16, 0xc7,
	0xed, 0x47, 0x6b, 0x2c, 0x89, 0x64, 0xae, 0x8b, 0xc8, 0x6e, 0xe0, 0xca, 0x3d, 0xe7, 0xfd, 0x30,
	0x4c, 0x35, 0x6a, 0xfa, 0x8a, 0xfd, 0xf3, 0x5e, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xbb, 0xc4,
	0x65, 0xe5, 0x49, 0x01, 0x00, 0x00,
}
