// Code generated by protoc-gen-go. DO NOT EDIT.
// source: M2C.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Hero struct {
	HeroId               int32    `protobuf:"varint,1,opt,name=heroId,proto3" json:"heroId,omitempty"`
	Level                int32    `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	ItemIds              []*Item  `protobuf:"bytes,3,rep,name=itemIds,proto3" json:"itemIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hero) Reset()         { *m = Hero{} }
func (m *Hero) String() string { return proto.CompactTextString(m) }
func (*Hero) ProtoMessage()    {}
func (*Hero) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{0}
}
func (m *Hero) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hero.Unmarshal(m, b)
}
func (m *Hero) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hero.Marshal(b, m, deterministic)
}
func (dst *Hero) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hero.Merge(dst, src)
}
func (m *Hero) XXX_Size() int {
	return xxx_messageInfo_Hero.Size(m)
}
func (m *Hero) XXX_DiscardUnknown() {
	xxx_messageInfo_Hero.DiscardUnknown(m)
}

var xxx_messageInfo_Hero proto.InternalMessageInfo

func (m *Hero) GetHeroId() int32 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *Hero) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Hero) GetItemIds() []*Item {
	if m != nil {
		return m.ItemIds
	}
	return nil
}

type Item struct {
	ItemId               int32    `protobuf:"varint,1,opt,name=itemId,proto3" json:"itemId,omitempty"`
	Index                int32    `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	ItemSeed             int32    `protobuf:"varint,3,opt,name=itemSeed,proto3" json:"itemSeed,omitempty"`
	ItemNum              int32    `protobuf:"varint,4,opt,name=itemNum,proto3" json:"itemNum,omitempty"`
	ItemTime             int64    `protobuf:"varint,5,opt,name=itemTime,proto3" json:"itemTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{1}
}
func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (dst *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(dst, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *Item) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Item) GetItemSeed() int32 {
	if m != nil {
		return m.ItemSeed
	}
	return 0
}

func (m *Item) GetItemNum() int32 {
	if m != nil {
		return m.ItemNum
	}
	return 0
}

func (m *Item) GetItemTime() int64 {
	if m != nil {
		return m.ItemTime
	}
	return 0
}

type RankListItem struct {
	RankNum              int32    `protobuf:"varint,1,opt,name=rankNum,proto3" json:"rankNum,omitempty"`
	RankLevel            int32    `protobuf:"varint,2,opt,name=rankLevel,proto3" json:"rankLevel,omitempty"`
	NickName             string   `protobuf:"bytes,3,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Value                int32    `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RankListItem) Reset()         { *m = RankListItem{} }
func (m *RankListItem) String() string { return proto.CompactTextString(m) }
func (*RankListItem) ProtoMessage()    {}
func (*RankListItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{2}
}
func (m *RankListItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankListItem.Unmarshal(m, b)
}
func (m *RankListItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankListItem.Marshal(b, m, deterministic)
}
func (dst *RankListItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankListItem.Merge(dst, src)
}
func (m *RankListItem) XXX_Size() int {
	return xxx_messageInfo_RankListItem.Size(m)
}
func (m *RankListItem) XXX_DiscardUnknown() {
	xxx_messageInfo_RankListItem.DiscardUnknown(m)
}

var xxx_messageInfo_RankListItem proto.InternalMessageInfo

func (m *RankListItem) GetRankNum() int32 {
	if m != nil {
		return m.RankNum
	}
	return 0
}

func (m *RankListItem) GetRankLevel() int32 {
	if m != nil {
		return m.RankLevel
	}
	return 0
}

func (m *RankListItem) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *RankListItem) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Email struct {
	EmailId              int32    `protobuf:"varint,1,opt,name=emailId,proto3" json:"emailId,omitempty"`
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	BGet                 bool     `protobuf:"varint,3,opt,name=bGet,proto3" json:"bGet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}
func (*Email) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{3}
}
func (m *Email) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Email.Unmarshal(m, b)
}
func (m *Email) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Email.Marshal(b, m, deterministic)
}
func (dst *Email) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Email.Merge(dst, src)
}
func (m *Email) XXX_Size() int {
	return xxx_messageInfo_Email.Size(m)
}
func (m *Email) XXX_DiscardUnknown() {
	xxx_messageInfo_Email.DiscardUnknown(m)
}

var xxx_messageInfo_Email proto.InternalMessageInfo

func (m *Email) GetEmailId() int32 {
	if m != nil {
		return m.EmailId
	}
	return 0
}

func (m *Email) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Email) GetBGet() bool {
	if m != nil {
		return m.BGet
	}
	return false
}

type M2C2M_GamePing struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C2M_GamePing) Reset()         { *m = M2C2M_GamePing{} }
func (m *M2C2M_GamePing) String() string { return proto.CompactTextString(m) }
func (*M2C2M_GamePing) ProtoMessage()    {}
func (*M2C2M_GamePing) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{4}
}
func (m *M2C2M_GamePing) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C2M_GamePing.Unmarshal(m, b)
}
func (m *M2C2M_GamePing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C2M_GamePing.Marshal(b, m, deterministic)
}
func (dst *M2C2M_GamePing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C2M_GamePing.Merge(dst, src)
}
func (m *M2C2M_GamePing) XXX_Size() int {
	return xxx_messageInfo_M2C2M_GamePing.Size(m)
}
func (m *M2C2M_GamePing) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C2M_GamePing.DiscardUnknown(m)
}

var xxx_messageInfo_M2C2M_GamePing proto.InternalMessageInfo

// 大厅数据
type M2C_EnterLobby struct {
	RoomId int32 `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	// 玩家数据
	RoleBasicInfo *Role `protobuf:"bytes,2,opt,name=roleBasicInfo,proto3" json:"roleBasicInfo,omitempty"`
	// 玩家英雄数据
	HeroInfo             []*Hero          `protobuf:"bytes,3,rep,name=heroInfo,proto3" json:"heroInfo,omitempty"`
	Items                []*Item          `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	BattleId             int32            `protobuf:"varint,5,opt,name=battleId,proto3" json:"battleId,omitempty"`
	TaskSeed             int32            `protobuf:"varint,6,opt,name=taskSeed,proto3" json:"taskSeed,omitempty"`
	Version              string           `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Arrower              *FreeSoldierData `protobuf:"bytes,8,opt,name=arrower,proto3" json:"arrower,omitempty"`
	Daodun               *FreeSoldierData `protobuf:"bytes,9,opt,name=daodun,proto3" json:"daodun,omitempty"`
	Spear                *FreeSoldierData `protobuf:"bytes,10,opt,name=spear,proto3" json:"spear,omitempty"`
	Fashi                *FreeSoldierData `protobuf:"bytes,11,opt,name=fashi,proto3" json:"fashi,omitempty"`
	Emails               []*Email         `protobuf:"bytes,12,rep,name=emails,proto3" json:"emails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *M2C_EnterLobby) Reset()         { *m = M2C_EnterLobby{} }
func (m *M2C_EnterLobby) String() string { return proto.CompactTextString(m) }
func (*M2C_EnterLobby) ProtoMessage()    {}
func (*M2C_EnterLobby) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{5}
}
func (m *M2C_EnterLobby) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_EnterLobby.Unmarshal(m, b)
}
func (m *M2C_EnterLobby) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_EnterLobby.Marshal(b, m, deterministic)
}
func (dst *M2C_EnterLobby) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_EnterLobby.Merge(dst, src)
}
func (m *M2C_EnterLobby) XXX_Size() int {
	return xxx_messageInfo_M2C_EnterLobby.Size(m)
}
func (m *M2C_EnterLobby) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_EnterLobby.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_EnterLobby proto.InternalMessageInfo

func (m *M2C_EnterLobby) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *M2C_EnterLobby) GetRoleBasicInfo() *Role {
	if m != nil {
		return m.RoleBasicInfo
	}
	return nil
}

func (m *M2C_EnterLobby) GetHeroInfo() []*Hero {
	if m != nil {
		return m.HeroInfo
	}
	return nil
}

func (m *M2C_EnterLobby) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *M2C_EnterLobby) GetBattleId() int32 {
	if m != nil {
		return m.BattleId
	}
	return 0
}

func (m *M2C_EnterLobby) GetTaskSeed() int32 {
	if m != nil {
		return m.TaskSeed
	}
	return 0
}

func (m *M2C_EnterLobby) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *M2C_EnterLobby) GetArrower() *FreeSoldierData {
	if m != nil {
		return m.Arrower
	}
	return nil
}

func (m *M2C_EnterLobby) GetDaodun() *FreeSoldierData {
	if m != nil {
		return m.Daodun
	}
	return nil
}

func (m *M2C_EnterLobby) GetSpear() *FreeSoldierData {
	if m != nil {
		return m.Spear
	}
	return nil
}

func (m *M2C_EnterLobby) GetFashi() *FreeSoldierData {
	if m != nil {
		return m.Fashi
	}
	return nil
}

func (m *M2C_EnterLobby) GetEmails() []*Email {
	if m != nil {
		return m.Emails
	}
	return nil
}

// 刷新房间列表
type M2C_RefreshRoomList struct {
	RoomList             []*Room  `protobuf:"bytes,1,rep,name=roomList,proto3" json:"roomList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_RefreshRoomList) Reset()         { *m = M2C_RefreshRoomList{} }
func (m *M2C_RefreshRoomList) String() string { return proto.CompactTextString(m) }
func (*M2C_RefreshRoomList) ProtoMessage()    {}
func (*M2C_RefreshRoomList) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{6}
}
func (m *M2C_RefreshRoomList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_RefreshRoomList.Unmarshal(m, b)
}
func (m *M2C_RefreshRoomList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_RefreshRoomList.Marshal(b, m, deterministic)
}
func (dst *M2C_RefreshRoomList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_RefreshRoomList.Merge(dst, src)
}
func (m *M2C_RefreshRoomList) XXX_Size() int {
	return xxx_messageInfo_M2C_RefreshRoomList.Size(m)
}
func (m *M2C_RefreshRoomList) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_RefreshRoomList.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_RefreshRoomList proto.InternalMessageInfo

func (m *M2C_RefreshRoomList) GetRoomList() []*Room {
	if m != nil {
		return m.RoomList
	}
	return nil
}

// 改变Room状态信息
type M2C_JoinRoom struct {
	Member               *RoomMember  `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	RoomId               int32        `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	RoomSetting          *RoomSetting `protobuf:"bytes,3,opt,name=roomSetting,proto3" json:"roomSetting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *M2C_JoinRoom) Reset()         { *m = M2C_JoinRoom{} }
func (m *M2C_JoinRoom) String() string { return proto.CompactTextString(m) }
func (*M2C_JoinRoom) ProtoMessage()    {}
func (*M2C_JoinRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{7}
}
func (m *M2C_JoinRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_JoinRoom.Unmarshal(m, b)
}
func (m *M2C_JoinRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_JoinRoom.Marshal(b, m, deterministic)
}
func (dst *M2C_JoinRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_JoinRoom.Merge(dst, src)
}
func (m *M2C_JoinRoom) XXX_Size() int {
	return xxx_messageInfo_M2C_JoinRoom.Size(m)
}
func (m *M2C_JoinRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_JoinRoom.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_JoinRoom proto.InternalMessageInfo

func (m *M2C_JoinRoom) GetMember() *RoomMember {
	if m != nil {
		return m.Member
	}
	return nil
}

func (m *M2C_JoinRoom) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *M2C_JoinRoom) GetRoomSetting() *RoomSetting {
	if m != nil {
		return m.RoomSetting
	}
	return nil
}

// 房间设置
type RoomSetting struct {
	MapId                int32    `protobuf:"varint,1,opt,name=mapId,proto3" json:"mapId,omitempty"`
	IsWarFow             bool     `protobuf:"varint,2,opt,name=isWarFow,proto3" json:"isWarFow,omitempty"`
	GameType             int32    `protobuf:"varint,3,opt,name=gameType,proto3" json:"gameType,omitempty"`
	BOutsideMonster      bool     `protobuf:"varint,4,opt,name=bOutsideMonster,proto3" json:"bOutsideMonster,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomSetting) Reset()         { *m = RoomSetting{} }
func (m *RoomSetting) String() string { return proto.CompactTextString(m) }
func (*RoomSetting) ProtoMessage()    {}
func (*RoomSetting) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{8}
}
func (m *RoomSetting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomSetting.Unmarshal(m, b)
}
func (m *RoomSetting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomSetting.Marshal(b, m, deterministic)
}
func (dst *RoomSetting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomSetting.Merge(dst, src)
}
func (m *RoomSetting) XXX_Size() int {
	return xxx_messageInfo_RoomSetting.Size(m)
}
func (m *RoomSetting) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomSetting.DiscardUnknown(m)
}

var xxx_messageInfo_RoomSetting proto.InternalMessageInfo

func (m *RoomSetting) GetMapId() int32 {
	if m != nil {
		return m.MapId
	}
	return 0
}

func (m *RoomSetting) GetIsWarFow() bool {
	if m != nil {
		return m.IsWarFow
	}
	return false
}

func (m *RoomSetting) GetGameType() int32 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *RoomSetting) GetBOutsideMonster() bool {
	if m != nil {
		return m.BOutsideMonster
	}
	return false
}

// 准备成功
type M2C_ReadySuccess struct {
	RoleId               int64    `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	Ready                bool     `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_ReadySuccess) Reset()         { *m = M2C_ReadySuccess{} }
func (m *M2C_ReadySuccess) String() string { return proto.CompactTextString(m) }
func (*M2C_ReadySuccess) ProtoMessage()    {}
func (*M2C_ReadySuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{9}
}
func (m *M2C_ReadySuccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_ReadySuccess.Unmarshal(m, b)
}
func (m *M2C_ReadySuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_ReadySuccess.Marshal(b, m, deterministic)
}
func (dst *M2C_ReadySuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_ReadySuccess.Merge(dst, src)
}
func (m *M2C_ReadySuccess) XXX_Size() int {
	return xxx_messageInfo_M2C_ReadySuccess.Size(m)
}
func (m *M2C_ReadySuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_ReadySuccess.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_ReadySuccess proto.InternalMessageInfo

func (m *M2C_ReadySuccess) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *M2C_ReadySuccess) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

// 开始战斗加载
type M2C_StartBattleLoad struct {
	AllReady             bool     `protobuf:"varint,1,opt,name=allReady,proto3" json:"allReady,omitempty"`
	Seed                 int32    `protobuf:"varint,2,opt,name=seed,proto3" json:"seed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_StartBattleLoad) Reset()         { *m = M2C_StartBattleLoad{} }
func (m *M2C_StartBattleLoad) String() string { return proto.CompactTextString(m) }
func (*M2C_StartBattleLoad) ProtoMessage()    {}
func (*M2C_StartBattleLoad) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{10}
}
func (m *M2C_StartBattleLoad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_StartBattleLoad.Unmarshal(m, b)
}
func (m *M2C_StartBattleLoad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_StartBattleLoad.Marshal(b, m, deterministic)
}
func (dst *M2C_StartBattleLoad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_StartBattleLoad.Merge(dst, src)
}
func (m *M2C_StartBattleLoad) XXX_Size() int {
	return xxx_messageInfo_M2C_StartBattleLoad.Size(m)
}
func (m *M2C_StartBattleLoad) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_StartBattleLoad.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_StartBattleLoad proto.InternalMessageInfo

func (m *M2C_StartBattleLoad) GetAllReady() bool {
	if m != nil {
		return m.AllReady
	}
	return false
}

func (m *M2C_StartBattleLoad) GetSeed() int32 {
	if m != nil {
		return m.Seed
	}
	return 0
}

// 开始战斗
type M2C_StartBattle struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_StartBattle) Reset()         { *m = M2C_StartBattle{} }
func (m *M2C_StartBattle) String() string { return proto.CompactTextString(m) }
func (*M2C_StartBattle) ProtoMessage()    {}
func (*M2C_StartBattle) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{11}
}
func (m *M2C_StartBattle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_StartBattle.Unmarshal(m, b)
}
func (m *M2C_StartBattle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_StartBattle.Marshal(b, m, deterministic)
}
func (dst *M2C_StartBattle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_StartBattle.Merge(dst, src)
}
func (m *M2C_StartBattle) XXX_Size() int {
	return xxx_messageInfo_M2C_StartBattle.Size(m)
}
func (m *M2C_StartBattle) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_StartBattle.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_StartBattle proto.InternalMessageInfo

// 每一帧的操作
type M2C_BattleFrame struct {
	FrameCount           int32      `protobuf:"varint,1,opt,name=frameCount,proto3" json:"frameCount,omitempty"`
	Cmd                  []*Command `protobuf:"bytes,2,rep,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *M2C_BattleFrame) Reset()         { *m = M2C_BattleFrame{} }
func (m *M2C_BattleFrame) String() string { return proto.CompactTextString(m) }
func (*M2C_BattleFrame) ProtoMessage()    {}
func (*M2C_BattleFrame) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{12}
}
func (m *M2C_BattleFrame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_BattleFrame.Unmarshal(m, b)
}
func (m *M2C_BattleFrame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_BattleFrame.Marshal(b, m, deterministic)
}
func (dst *M2C_BattleFrame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_BattleFrame.Merge(dst, src)
}
func (m *M2C_BattleFrame) XXX_Size() int {
	return xxx_messageInfo_M2C_BattleFrame.Size(m)
}
func (m *M2C_BattleFrame) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_BattleFrame.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_BattleFrame proto.InternalMessageInfo

func (m *M2C_BattleFrame) GetFrameCount() int32 {
	if m != nil {
		return m.FrameCount
	}
	return 0
}

func (m *M2C_BattleFrame) GetCmd() []*Command {
	if m != nil {
		return m.Cmd
	}
	return nil
}

// 删除房间
type M2C_RoomDelete struct {
	RoomId               int32    `protobuf:"varint,1,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_RoomDelete) Reset()         { *m = M2C_RoomDelete{} }
func (m *M2C_RoomDelete) String() string { return proto.CompactTextString(m) }
func (*M2C_RoomDelete) ProtoMessage()    {}
func (*M2C_RoomDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{13}
}
func (m *M2C_RoomDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_RoomDelete.Unmarshal(m, b)
}
func (m *M2C_RoomDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_RoomDelete.Marshal(b, m, deterministic)
}
func (dst *M2C_RoomDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_RoomDelete.Merge(dst, src)
}
func (m *M2C_RoomDelete) XXX_Size() int {
	return xxx_messageInfo_M2C_RoomDelete.Size(m)
}
func (m *M2C_RoomDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_RoomDelete.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_RoomDelete proto.InternalMessageInfo

func (m *M2C_RoomDelete) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

// 退出房间
type M2C_RoleQuitRoom struct {
	RoleId               int64    `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	RoomId               int32    `protobuf:"varint,2,opt,name=roomId,proto3" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_RoleQuitRoom) Reset()         { *m = M2C_RoleQuitRoom{} }
func (m *M2C_RoleQuitRoom) String() string { return proto.CompactTextString(m) }
func (*M2C_RoleQuitRoom) ProtoMessage()    {}
func (*M2C_RoleQuitRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{14}
}
func (m *M2C_RoleQuitRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_RoleQuitRoom.Unmarshal(m, b)
}
func (m *M2C_RoleQuitRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_RoleQuitRoom.Marshal(b, m, deterministic)
}
func (dst *M2C_RoleQuitRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_RoleQuitRoom.Merge(dst, src)
}
func (m *M2C_RoleQuitRoom) XXX_Size() int {
	return xxx_messageInfo_M2C_RoleQuitRoom.Size(m)
}
func (m *M2C_RoleQuitRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_RoleQuitRoom.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_RoleQuitRoom proto.InternalMessageInfo

func (m *M2C_RoleQuitRoom) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *M2C_RoleQuitRoom) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

// 战役结果
type M2C_BattleResult struct {
	Award1               int32    `protobuf:"varint,1,opt,name=award1,proto3" json:"award1,omitempty"`
	Award2               int32    `protobuf:"varint,2,opt,name=award2,proto3" json:"award2,omitempty"`
	Award3               int32    `protobuf:"varint,3,opt,name=award3,proto3" json:"award3,omitempty"`
	Index1               int32    `protobuf:"varint,4,opt,name=index1,proto3" json:"index1,omitempty"`
	Index2               int32    `protobuf:"varint,5,opt,name=index2,proto3" json:"index2,omitempty"`
	Index3               int32    `protobuf:"varint,6,opt,name=index3,proto3" json:"index3,omitempty"`
	Seed                 int32    `protobuf:"varint,7,opt,name=seed,proto3" json:"seed,omitempty"`
	NowTime              int64    `protobuf:"varint,8,opt,name=nowTime,proto3" json:"nowTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_BattleResult) Reset()         { *m = M2C_BattleResult{} }
func (m *M2C_BattleResult) String() string { return proto.CompactTextString(m) }
func (*M2C_BattleResult) ProtoMessage()    {}
func (*M2C_BattleResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{15}
}
func (m *M2C_BattleResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_BattleResult.Unmarshal(m, b)
}
func (m *M2C_BattleResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_BattleResult.Marshal(b, m, deterministic)
}
func (dst *M2C_BattleResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_BattleResult.Merge(dst, src)
}
func (m *M2C_BattleResult) XXX_Size() int {
	return xxx_messageInfo_M2C_BattleResult.Size(m)
}
func (m *M2C_BattleResult) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_BattleResult.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_BattleResult proto.InternalMessageInfo

func (m *M2C_BattleResult) GetAward1() int32 {
	if m != nil {
		return m.Award1
	}
	return 0
}

func (m *M2C_BattleResult) GetAward2() int32 {
	if m != nil {
		return m.Award2
	}
	return 0
}

func (m *M2C_BattleResult) GetAward3() int32 {
	if m != nil {
		return m.Award3
	}
	return 0
}

func (m *M2C_BattleResult) GetIndex1() int32 {
	if m != nil {
		return m.Index1
	}
	return 0
}

func (m *M2C_BattleResult) GetIndex2() int32 {
	if m != nil {
		return m.Index2
	}
	return 0
}

func (m *M2C_BattleResult) GetIndex3() int32 {
	if m != nil {
		return m.Index3
	}
	return 0
}

func (m *M2C_BattleResult) GetSeed() int32 {
	if m != nil {
		return m.Seed
	}
	return 0
}

func (m *M2C_BattleResult) GetNowTime() int64 {
	if m != nil {
		return m.NowTime
	}
	return 0
}

// 观看广告结果
type M2C_WatchAdsResult struct {
	BoxId                int32    `protobuf:"varint,1,opt,name=boxId,proto3" json:"boxId,omitempty"`
	Seed                 int32    `protobuf:"varint,2,opt,name=seed,proto3" json:"seed,omitempty"`
	Index                int32    `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	NowTime              int64    `protobuf:"varint,4,opt,name=nowTime,proto3" json:"nowTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_WatchAdsResult) Reset()         { *m = M2C_WatchAdsResult{} }
func (m *M2C_WatchAdsResult) String() string { return proto.CompactTextString(m) }
func (*M2C_WatchAdsResult) ProtoMessage()    {}
func (*M2C_WatchAdsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{16}
}
func (m *M2C_WatchAdsResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_WatchAdsResult.Unmarshal(m, b)
}
func (m *M2C_WatchAdsResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_WatchAdsResult.Marshal(b, m, deterministic)
}
func (dst *M2C_WatchAdsResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_WatchAdsResult.Merge(dst, src)
}
func (m *M2C_WatchAdsResult) XXX_Size() int {
	return xxx_messageInfo_M2C_WatchAdsResult.Size(m)
}
func (m *M2C_WatchAdsResult) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_WatchAdsResult.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_WatchAdsResult proto.InternalMessageInfo

func (m *M2C_WatchAdsResult) GetBoxId() int32 {
	if m != nil {
		return m.BoxId
	}
	return 0
}

func (m *M2C_WatchAdsResult) GetSeed() int32 {
	if m != nil {
		return m.Seed
	}
	return 0
}

func (m *M2C_WatchAdsResult) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *M2C_WatchAdsResult) GetNowTime() int64 {
	if m != nil {
		return m.NowTime
	}
	return 0
}

// 修改昵称结果
type M2C_ChangeNickName struct {
	ResultName           string   `protobuf:"bytes,1,opt,name=resultName,proto3" json:"resultName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_ChangeNickName) Reset()         { *m = M2C_ChangeNickName{} }
func (m *M2C_ChangeNickName) String() string { return proto.CompactTextString(m) }
func (*M2C_ChangeNickName) ProtoMessage()    {}
func (*M2C_ChangeNickName) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{17}
}
func (m *M2C_ChangeNickName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_ChangeNickName.Unmarshal(m, b)
}
func (m *M2C_ChangeNickName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_ChangeNickName.Marshal(b, m, deterministic)
}
func (dst *M2C_ChangeNickName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_ChangeNickName.Merge(dst, src)
}
func (m *M2C_ChangeNickName) XXX_Size() int {
	return xxx_messageInfo_M2C_ChangeNickName.Size(m)
}
func (m *M2C_ChangeNickName) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_ChangeNickName.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_ChangeNickName proto.InternalMessageInfo

func (m *M2C_ChangeNickName) GetResultName() string {
	if m != nil {
		return m.ResultName
	}
	return ""
}

// 修改头像结果
type M2C_ChangeAvatarIcon struct {
	AvatarId             int32    `protobuf:"varint,1,opt,name=avatarId,proto3" json:"avatarId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_ChangeAvatarIcon) Reset()         { *m = M2C_ChangeAvatarIcon{} }
func (m *M2C_ChangeAvatarIcon) String() string { return proto.CompactTextString(m) }
func (*M2C_ChangeAvatarIcon) ProtoMessage()    {}
func (*M2C_ChangeAvatarIcon) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{18}
}
func (m *M2C_ChangeAvatarIcon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_ChangeAvatarIcon.Unmarshal(m, b)
}
func (m *M2C_ChangeAvatarIcon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_ChangeAvatarIcon.Marshal(b, m, deterministic)
}
func (dst *M2C_ChangeAvatarIcon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_ChangeAvatarIcon.Merge(dst, src)
}
func (m *M2C_ChangeAvatarIcon) XXX_Size() int {
	return xxx_messageInfo_M2C_ChangeAvatarIcon.Size(m)
}
func (m *M2C_ChangeAvatarIcon) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_ChangeAvatarIcon.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_ChangeAvatarIcon proto.InternalMessageInfo

func (m *M2C_ChangeAvatarIcon) GetAvatarId() int32 {
	if m != nil {
		return m.AvatarId
	}
	return 0
}

// 修改性别结果
type M2C_ChangeSexResult struct {
	Sex                  int32    `protobuf:"varint,1,opt,name=sex,proto3" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_ChangeSexResult) Reset()         { *m = M2C_ChangeSexResult{} }
func (m *M2C_ChangeSexResult) String() string { return proto.CompactTextString(m) }
func (*M2C_ChangeSexResult) ProtoMessage()    {}
func (*M2C_ChangeSexResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{19}
}
func (m *M2C_ChangeSexResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_ChangeSexResult.Unmarshal(m, b)
}
func (m *M2C_ChangeSexResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_ChangeSexResult.Marshal(b, m, deterministic)
}
func (dst *M2C_ChangeSexResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_ChangeSexResult.Merge(dst, src)
}
func (m *M2C_ChangeSexResult) XXX_Size() int {
	return xxx_messageInfo_M2C_ChangeSexResult.Size(m)
}
func (m *M2C_ChangeSexResult) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_ChangeSexResult.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_ChangeSexResult proto.InternalMessageInfo

func (m *M2C_ChangeSexResult) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

// 玩家签名修改
type M2C_ChangeSignResult struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_ChangeSignResult) Reset()         { *m = M2C_ChangeSignResult{} }
func (m *M2C_ChangeSignResult) String() string { return proto.CompactTextString(m) }
func (*M2C_ChangeSignResult) ProtoMessage()    {}
func (*M2C_ChangeSignResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{20}
}
func (m *M2C_ChangeSignResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_ChangeSignResult.Unmarshal(m, b)
}
func (m *M2C_ChangeSignResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_ChangeSignResult.Marshal(b, m, deterministic)
}
func (dst *M2C_ChangeSignResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_ChangeSignResult.Merge(dst, src)
}
func (m *M2C_ChangeSignResult) XXX_Size() int {
	return xxx_messageInfo_M2C_ChangeSignResult.Size(m)
}
func (m *M2C_ChangeSignResult) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_ChangeSignResult.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_ChangeSignResult proto.InternalMessageInfo

func (m *M2C_ChangeSignResult) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// 重连战斗数据
type M2C_ReBattleConnect struct {
	RoomInfo *Room `protobuf:"bytes,1,opt,name=roomInfo,proto3" json:"roomInfo,omitempty"`
	// RoomSetting roomSetting = 2
	Commands             []*SaveCommandList `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	Seed                 int32              `protobuf:"varint,3,opt,name=seed,proto3" json:"seed,omitempty"`
	FrameCount           int32              `protobuf:"varint,4,opt,name=frameCount,proto3" json:"frameCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *M2C_ReBattleConnect) Reset()         { *m = M2C_ReBattleConnect{} }
func (m *M2C_ReBattleConnect) String() string { return proto.CompactTextString(m) }
func (*M2C_ReBattleConnect) ProtoMessage()    {}
func (*M2C_ReBattleConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{21}
}
func (m *M2C_ReBattleConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_ReBattleConnect.Unmarshal(m, b)
}
func (m *M2C_ReBattleConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_ReBattleConnect.Marshal(b, m, deterministic)
}
func (dst *M2C_ReBattleConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_ReBattleConnect.Merge(dst, src)
}
func (m *M2C_ReBattleConnect) XXX_Size() int {
	return xxx_messageInfo_M2C_ReBattleConnect.Size(m)
}
func (m *M2C_ReBattleConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_ReBattleConnect.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_ReBattleConnect proto.InternalMessageInfo

func (m *M2C_ReBattleConnect) GetRoomInfo() *Room {
	if m != nil {
		return m.RoomInfo
	}
	return nil
}

func (m *M2C_ReBattleConnect) GetCommands() []*SaveCommandList {
	if m != nil {
		return m.Commands
	}
	return nil
}

func (m *M2C_ReBattleConnect) GetSeed() int32 {
	if m != nil {
		return m.Seed
	}
	return 0
}

func (m *M2C_ReBattleConnect) GetFrameCount() int32 {
	if m != nil {
		return m.FrameCount
	}
	return 0
}

// 重连房间数据
type M2C_ReRoomConnect struct {
	RoomInfo             *Room    `protobuf:"bytes,1,opt,name=roomInfo,proto3" json:"roomInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_ReRoomConnect) Reset()         { *m = M2C_ReRoomConnect{} }
func (m *M2C_ReRoomConnect) String() string { return proto.CompactTextString(m) }
func (*M2C_ReRoomConnect) ProtoMessage()    {}
func (*M2C_ReRoomConnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{22}
}
func (m *M2C_ReRoomConnect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_ReRoomConnect.Unmarshal(m, b)
}
func (m *M2C_ReRoomConnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_ReRoomConnect.Marshal(b, m, deterministic)
}
func (dst *M2C_ReRoomConnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_ReRoomConnect.Merge(dst, src)
}
func (m *M2C_ReRoomConnect) XXX_Size() int {
	return xxx_messageInfo_M2C_ReRoomConnect.Size(m)
}
func (m *M2C_ReRoomConnect) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_ReRoomConnect.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_ReRoomConnect proto.InternalMessageInfo

func (m *M2C_ReRoomConnect) GetRoomInfo() *Room {
	if m != nil {
		return m.RoomInfo
	}
	return nil
}

// 重连帧数
type SaveCommandList struct {
	FrameIndex           int32      `protobuf:"varint,1,opt,name=frameIndex,proto3" json:"frameIndex,omitempty"`
	Cmds                 []*Command `protobuf:"bytes,2,rep,name=cmds,proto3" json:"cmds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SaveCommandList) Reset()         { *m = SaveCommandList{} }
func (m *SaveCommandList) String() string { return proto.CompactTextString(m) }
func (*SaveCommandList) ProtoMessage()    {}
func (*SaveCommandList) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{23}
}
func (m *SaveCommandList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveCommandList.Unmarshal(m, b)
}
func (m *SaveCommandList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveCommandList.Marshal(b, m, deterministic)
}
func (dst *SaveCommandList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveCommandList.Merge(dst, src)
}
func (m *SaveCommandList) XXX_Size() int {
	return xxx_messageInfo_SaveCommandList.Size(m)
}
func (m *SaveCommandList) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveCommandList.DiscardUnknown(m)
}

var xxx_messageInfo_SaveCommandList proto.InternalMessageInfo

func (m *SaveCommandList) GetFrameIndex() int32 {
	if m != nil {
		return m.FrameIndex
	}
	return 0
}

func (m *SaveCommandList) GetCmds() []*Command {
	if m != nil {
		return m.Cmds
	}
	return nil
}

// 买英雄结果
type M2C_BuyHeroResult struct {
	HeroId               int32    `protobuf:"varint,1,opt,name=heroId,proto3" json:"heroId,omitempty"`
	ResultCode           int32    `protobuf:"varint,2,opt,name=resultCode,proto3" json:"resultCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_BuyHeroResult) Reset()         { *m = M2C_BuyHeroResult{} }
func (m *M2C_BuyHeroResult) String() string { return proto.CompactTextString(m) }
func (*M2C_BuyHeroResult) ProtoMessage()    {}
func (*M2C_BuyHeroResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{24}
}
func (m *M2C_BuyHeroResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_BuyHeroResult.Unmarshal(m, b)
}
func (m *M2C_BuyHeroResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_BuyHeroResult.Marshal(b, m, deterministic)
}
func (dst *M2C_BuyHeroResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_BuyHeroResult.Merge(dst, src)
}
func (m *M2C_BuyHeroResult) XXX_Size() int {
	return xxx_messageInfo_M2C_BuyHeroResult.Size(m)
}
func (m *M2C_BuyHeroResult) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_BuyHeroResult.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_BuyHeroResult proto.InternalMessageInfo

func (m *M2C_BuyHeroResult) GetHeroId() int32 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *M2C_BuyHeroResult) GetResultCode() int32 {
	if m != nil {
		return m.ResultCode
	}
	return 0
}

// 学习结果
type M2C_LearnSkillResult struct {
	SkillId              int32    `protobuf:"varint,1,opt,name=skillId,proto3" json:"skillId,omitempty"`
	HeroId               int32    `protobuf:"varint,2,opt,name=heroId,proto3" json:"heroId,omitempty"`
	SkillPoint           int32    `protobuf:"varint,3,opt,name=skillPoint,proto3" json:"skillPoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_LearnSkillResult) Reset()         { *m = M2C_LearnSkillResult{} }
func (m *M2C_LearnSkillResult) String() string { return proto.CompactTextString(m) }
func (*M2C_LearnSkillResult) ProtoMessage()    {}
func (*M2C_LearnSkillResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{25}
}
func (m *M2C_LearnSkillResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_LearnSkillResult.Unmarshal(m, b)
}
func (m *M2C_LearnSkillResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_LearnSkillResult.Marshal(b, m, deterministic)
}
func (dst *M2C_LearnSkillResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_LearnSkillResult.Merge(dst, src)
}
func (m *M2C_LearnSkillResult) XXX_Size() int {
	return xxx_messageInfo_M2C_LearnSkillResult.Size(m)
}
func (m *M2C_LearnSkillResult) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_LearnSkillResult.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_LearnSkillResult proto.InternalMessageInfo

func (m *M2C_LearnSkillResult) GetSkillId() int32 {
	if m != nil {
		return m.SkillId
	}
	return 0
}

func (m *M2C_LearnSkillResult) GetHeroId() int32 {
	if m != nil {
		return m.HeroId
	}
	return 0
}

func (m *M2C_LearnSkillResult) GetSkillPoint() int32 {
	if m != nil {
		return m.SkillPoint
	}
	return 0
}

// 打开宝箱获得奖励
type M2C_GetBoxAwardResult struct {
	ItemList             []*Item  `protobuf:"bytes,1,rep,name=itemList,proto3" json:"itemList,omitempty"`
	BoxItemIndex         int32    `protobuf:"varint,2,opt,name=boxItemIndex,proto3" json:"boxItemIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_GetBoxAwardResult) Reset()         { *m = M2C_GetBoxAwardResult{} }
func (m *M2C_GetBoxAwardResult) String() string { return proto.CompactTextString(m) }
func (*M2C_GetBoxAwardResult) ProtoMessage()    {}
func (*M2C_GetBoxAwardResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{26}
}
func (m *M2C_GetBoxAwardResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_GetBoxAwardResult.Unmarshal(m, b)
}
func (m *M2C_GetBoxAwardResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_GetBoxAwardResult.Marshal(b, m, deterministic)
}
func (dst *M2C_GetBoxAwardResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_GetBoxAwardResult.Merge(dst, src)
}
func (m *M2C_GetBoxAwardResult) XXX_Size() int {
	return xxx_messageInfo_M2C_GetBoxAwardResult.Size(m)
}
func (m *M2C_GetBoxAwardResult) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_GetBoxAwardResult.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_GetBoxAwardResult proto.InternalMessageInfo

func (m *M2C_GetBoxAwardResult) GetItemList() []*Item {
	if m != nil {
		return m.ItemList
	}
	return nil
}

func (m *M2C_GetBoxAwardResult) GetBoxItemIndex() int32 {
	if m != nil {
		return m.BoxItemIndex
	}
	return 0
}

// 打开邮箱获得奖励
type M2C_GetEmailResult struct {
	EmailId              int32    `protobuf:"varint,1,opt,name=emailId,proto3" json:"emailId,omitempty"`
	AwardItem            []*Item  `protobuf:"bytes,2,rep,name=awardItem,proto3" json:"awardItem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_GetEmailResult) Reset()         { *m = M2C_GetEmailResult{} }
func (m *M2C_GetEmailResult) String() string { return proto.CompactTextString(m) }
func (*M2C_GetEmailResult) ProtoMessage()    {}
func (*M2C_GetEmailResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{27}
}
func (m *M2C_GetEmailResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_GetEmailResult.Unmarshal(m, b)
}
func (m *M2C_GetEmailResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_GetEmailResult.Marshal(b, m, deterministic)
}
func (dst *M2C_GetEmailResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_GetEmailResult.Merge(dst, src)
}
func (m *M2C_GetEmailResult) XXX_Size() int {
	return xxx_messageInfo_M2C_GetEmailResult.Size(m)
}
func (m *M2C_GetEmailResult) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_GetEmailResult.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_GetEmailResult proto.InternalMessageInfo

func (m *M2C_GetEmailResult) GetEmailId() int32 {
	if m != nil {
		return m.EmailId
	}
	return 0
}

func (m *M2C_GetEmailResult) GetAwardItem() []*Item {
	if m != nil {
		return m.AwardItem
	}
	return nil
}

// 卖物品结果
type M2C_SellItemResult struct {
	ItemIndex            int32    `protobuf:"varint,1,opt,name=itemIndex,proto3" json:"itemIndex,omitempty"`
	RoleGold             int32    `protobuf:"varint,2,opt,name=roleGold,proto3" json:"roleGold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_SellItemResult) Reset()         { *m = M2C_SellItemResult{} }
func (m *M2C_SellItemResult) String() string { return proto.CompactTextString(m) }
func (*M2C_SellItemResult) ProtoMessage()    {}
func (*M2C_SellItemResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{28}
}
func (m *M2C_SellItemResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_SellItemResult.Unmarshal(m, b)
}
func (m *M2C_SellItemResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_SellItemResult.Marshal(b, m, deterministic)
}
func (dst *M2C_SellItemResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_SellItemResult.Merge(dst, src)
}
func (m *M2C_SellItemResult) XXX_Size() int {
	return xxx_messageInfo_M2C_SellItemResult.Size(m)
}
func (m *M2C_SellItemResult) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_SellItemResult.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_SellItemResult proto.InternalMessageInfo

func (m *M2C_SellItemResult) GetItemIndex() int32 {
	if m != nil {
		return m.ItemIndex
	}
	return 0
}

func (m *M2C_SellItemResult) GetRoleGold() int32 {
	if m != nil {
		return m.RoleGold
	}
	return 0
}

// 增加邮件
type M2C_AddEmai struct {
	Email                *Email   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_AddEmai) Reset()         { *m = M2C_AddEmai{} }
func (m *M2C_AddEmai) String() string { return proto.CompactTextString(m) }
func (*M2C_AddEmai) ProtoMessage()    {}
func (*M2C_AddEmai) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{29}
}
func (m *M2C_AddEmai) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_AddEmai.Unmarshal(m, b)
}
func (m *M2C_AddEmai) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_AddEmai.Marshal(b, m, deterministic)
}
func (dst *M2C_AddEmai) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_AddEmai.Merge(dst, src)
}
func (m *M2C_AddEmai) XXX_Size() int {
	return xxx_messageInfo_M2C_AddEmai.Size(m)
}
func (m *M2C_AddEmai) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_AddEmai.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_AddEmai proto.InternalMessageInfo

func (m *M2C_AddEmai) GetEmail() *Email {
	if m != nil {
		return m.Email
	}
	return nil
}

// 使用物品结果
type M2C_UseItemResult struct {
	ItemIndex            int32    `protobuf:"varint,1,opt,name=itemIndex,proto3" json:"itemIndex,omitempty"`
	ItemId               int32    `protobuf:"varint,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	ItemNum              int32    `protobuf:"varint,3,opt,name=itemNum,proto3" json:"itemNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_UseItemResult) Reset()         { *m = M2C_UseItemResult{} }
func (m *M2C_UseItemResult) String() string { return proto.CompactTextString(m) }
func (*M2C_UseItemResult) ProtoMessage()    {}
func (*M2C_UseItemResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{30}
}
func (m *M2C_UseItemResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_UseItemResult.Unmarshal(m, b)
}
func (m *M2C_UseItemResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_UseItemResult.Marshal(b, m, deterministic)
}
func (dst *M2C_UseItemResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_UseItemResult.Merge(dst, src)
}
func (m *M2C_UseItemResult) XXX_Size() int {
	return xxx_messageInfo_M2C_UseItemResult.Size(m)
}
func (m *M2C_UseItemResult) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_UseItemResult.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_UseItemResult proto.InternalMessageInfo

func (m *M2C_UseItemResult) GetItemIndex() int32 {
	if m != nil {
		return m.ItemIndex
	}
	return 0
}

func (m *M2C_UseItemResult) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *M2C_UseItemResult) GetItemNum() int32 {
	if m != nil {
		return m.ItemNum
	}
	return 0
}

// 开始暂停或者恢复
type M2C_StartPause struct {
	Pause                bool     `protobuf:"varint,1,opt,name=pause,proto3" json:"pause,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2C_StartPause) Reset()         { *m = M2C_StartPause{} }
func (m *M2C_StartPause) String() string { return proto.CompactTextString(m) }
func (*M2C_StartPause) ProtoMessage()    {}
func (*M2C_StartPause) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{31}
}
func (m *M2C_StartPause) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_StartPause.Unmarshal(m, b)
}
func (m *M2C_StartPause) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_StartPause.Marshal(b, m, deterministic)
}
func (dst *M2C_StartPause) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_StartPause.Merge(dst, src)
}
func (m *M2C_StartPause) XXX_Size() int {
	return xxx_messageInfo_M2C_StartPause.Size(m)
}
func (m *M2C_StartPause) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_StartPause.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_StartPause proto.InternalMessageInfo

func (m *M2C_StartPause) GetPause() bool {
	if m != nil {
		return m.Pause
	}
	return false
}

// 服务器发送的排行榜信息
type M2C_RankListResult struct {
	RankType             ERankListType   `protobuf:"varint,1,opt,name=rankType,proto3,enum=message.ERankListType" json:"rankType,omitempty"`
	RankListItem         []*RankListItem `protobuf:"bytes,2,rep,name=rankListItem,proto3" json:"rankListItem,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *M2C_RankListResult) Reset()         { *m = M2C_RankListResult{} }
func (m *M2C_RankListResult) String() string { return proto.CompactTextString(m) }
func (*M2C_RankListResult) ProtoMessage()    {}
func (*M2C_RankListResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2C_c9dd422ed3364cf9, []int{32}
}
func (m *M2C_RankListResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2C_RankListResult.Unmarshal(m, b)
}
func (m *M2C_RankListResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2C_RankListResult.Marshal(b, m, deterministic)
}
func (dst *M2C_RankListResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2C_RankListResult.Merge(dst, src)
}
func (m *M2C_RankListResult) XXX_Size() int {
	return xxx_messageInfo_M2C_RankListResult.Size(m)
}
func (m *M2C_RankListResult) XXX_DiscardUnknown() {
	xxx_messageInfo_M2C_RankListResult.DiscardUnknown(m)
}

var xxx_messageInfo_M2C_RankListResult proto.InternalMessageInfo

func (m *M2C_RankListResult) GetRankType() ERankListType {
	if m != nil {
		return m.RankType
	}
	return ERankListType_RankLevelIndex
}

func (m *M2C_RankListResult) GetRankListItem() []*RankListItem {
	if m != nil {
		return m.RankListItem
	}
	return nil
}

func init() {
	proto.RegisterType((*Hero)(nil), "message.Hero")
	proto.RegisterType((*Item)(nil), "message.Item")
	proto.RegisterType((*RankListItem)(nil), "message.RankListItem")
	proto.RegisterType((*Email)(nil), "message.Email")
	proto.RegisterType((*M2C2M_GamePing)(nil), "message.M2C2M_GamePing")
	proto.RegisterType((*M2C_EnterLobby)(nil), "message.M2C_EnterLobby")
	proto.RegisterType((*M2C_RefreshRoomList)(nil), "message.M2C_RefreshRoomList")
	proto.RegisterType((*M2C_JoinRoom)(nil), "message.M2C_JoinRoom")
	proto.RegisterType((*RoomSetting)(nil), "message.RoomSetting")
	proto.RegisterType((*M2C_ReadySuccess)(nil), "message.M2C_ReadySuccess")
	proto.RegisterType((*M2C_StartBattleLoad)(nil), "message.M2C_StartBattleLoad")
	proto.RegisterType((*M2C_StartBattle)(nil), "message.M2C_StartBattle")
	proto.RegisterType((*M2C_BattleFrame)(nil), "message.M2C_BattleFrame")
	proto.RegisterType((*M2C_RoomDelete)(nil), "message.M2C_RoomDelete")
	proto.RegisterType((*M2C_RoleQuitRoom)(nil), "message.M2C_RoleQuitRoom")
	proto.RegisterType((*M2C_BattleResult)(nil), "message.M2C_BattleResult")
	proto.RegisterType((*M2C_WatchAdsResult)(nil), "message.M2C_WatchAdsResult")
	proto.RegisterType((*M2C_ChangeNickName)(nil), "message.M2C_ChangeNickName")
	proto.RegisterType((*M2C_ChangeAvatarIcon)(nil), "message.M2C_ChangeAvatarIcon")
	proto.RegisterType((*M2C_ChangeSexResult)(nil), "message.M2C_ChangeSexResult")
	proto.RegisterType((*M2C_ChangeSignResult)(nil), "message.M2C_ChangeSignResult")
	proto.RegisterType((*M2C_ReBattleConnect)(nil), "message.M2C_ReBattleConnect")
	proto.RegisterType((*M2C_ReRoomConnect)(nil), "message.M2C_ReRoomConnect")
	proto.RegisterType((*SaveCommandList)(nil), "message.SaveCommandList")
	proto.RegisterType((*M2C_BuyHeroResult)(nil), "message.M2C_BuyHeroResult")
	proto.RegisterType((*M2C_LearnSkillResult)(nil), "message.M2C_LearnSkillResult")
	proto.RegisterType((*M2C_GetBoxAwardResult)(nil), "message.M2C_GetBoxAwardResult")
	proto.RegisterType((*M2C_GetEmailResult)(nil), "message.M2C_GetEmailResult")
	proto.RegisterType((*M2C_SellItemResult)(nil), "message.M2C_SellItemResult")
	proto.RegisterType((*M2C_AddEmai)(nil), "message.M2C_AddEmai")
	proto.RegisterType((*M2C_UseItemResult)(nil), "message.M2C_UseItemResult")
	proto.RegisterType((*M2C_StartPause)(nil), "message.M2C_StartPause")
	proto.RegisterType((*M2C_RankListResult)(nil), "message.M2C_RankListResult")
}

func init() { proto.RegisterFile("M2C.proto", fileDescriptor_M2C_c9dd422ed3364cf9) }

var fileDescriptor_M2C_c9dd422ed3364cf9 = []byte{
	// 1325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0x5f, 0x6f, 0xdb, 0x46,
	0x0c, 0x87, 0x62, 0x3b, 0xb1, 0xe9, 0xb4, 0x4d, 0xd5, 0xb4, 0x10, 0x8a, 0xa2, 0x28, 0x6e, 0x45,
	0x9b, 0xa2, 0x40, 0xb0, 0x2a, 0xc5, 0x80, 0xbd, 0x0c, 0x4d, 0xdc, 0x36, 0xf3, 0x96, 0x64, 0x9d,
	0xdc, 0xa2, 0x0f, 0xc3, 0x50, 0x9c, 0x2d, 0x26, 0x11, 0x22, 0xe9, 0x82, 0xd3, 0x39, 0x7f, 0x9e,
	0x87, 0xed, 0x65, 0xdf, 0x64, 0x9f, 0x66, 0x5f, 0x64, 0xdf, 0x61, 0x20, 0xef, 0x74, 0x96, 0xdd,
	0x04, 0xdd, 0xde, 0xee, 0x47, 0x52, 0x24, 0x8f, 0xe4, 0x91, 0x14, 0xf4, 0xf6, 0xe3, 0xc1, 0xe6,
	0xa9, 0x56, 0x46, 0x85, 0x2b, 0x05, 0x56, 0x95, 0x3c, 0xc2, 0xfb, 0xbd, 0x41, 0xbc, 0x6f, 0x69,
	0xf7, 0x7b, 0xbb, 0x35, 0x5b, 0xfc, 0x0a, 0xed, 0xef, 0x51, 0xab, 0xf0, 0x1e, 0x2c, 0x1f, 0xa3,
	0x56, 0xc3, 0x34, 0x0a, 0x1e, 0x05, 0x1b, 0x9d, 0xc4, 0xa1, 0x70, 0x1d, 0x3a, 0x39, 0x9e, 0x61,
	0x1e, 0x2d, 0x31, 0xd9, 0x82, 0xf0, 0x29, 0xac, 0x64, 0x06, 0x8b, 0x61, 0x5a, 0x45, 0xad, 0x47,
	0xad, 0x8d, 0x7e, 0x7c, 0x63, 0xd3, 0x99, 0xd9, 0x1c, 0x1a, 0x2c, 0x92, 0x9a, 0x2b, 0xfe, 0x08,
	0xa0, 0x4d, 0x14, 0xd2, 0x6f, 0x69, 0xb5, 0x7e, 0x8b, 0x48, 0x7f, 0x56, 0xa6, 0x78, 0x51, 0xeb,
	0x67, 0x10, 0xde, 0x87, 0x2e, 0xf1, 0x47, 0x88, 0x69, 0xd4, 0x62, 0x86, 0xc7, 0x61, 0x64, 0x6d,
	0x1f, 0x4c, 0x8b, 0xa8, 0xcd, 0xac, 0x1a, 0xd6, 0x5f, 0xbd, 0xcf, 0x0a, 0x8c, 0x3a, 0x8f, 0x82,
	0x8d, 0x56, 0xe2, 0xb1, 0xb8, 0x80, 0xd5, 0x44, 0x96, 0x27, 0x7b, 0x59, 0x65, 0xd8, 0x9f, 0x08,
	0x56, 0xb4, 0x2c, 0x4f, 0x48, 0x8b, 0x75, 0xa8, 0x86, 0xe1, 0x03, 0xe8, 0xd1, 0x71, 0xaf, 0x71,
	0xeb, 0x19, 0x81, 0x6c, 0x94, 0xd9, 0xe4, 0xe4, 0x40, 0x16, 0xc8, 0x9e, 0xf5, 0x12, 0x8f, 0xe9,
	0x2e, 0x67, 0x32, 0x9f, 0xa2, 0xf3, 0xcb, 0x02, 0x31, 0x84, 0xce, 0x9b, 0x42, 0x66, 0x39, 0x99,
	0x44, 0x3a, 0xf8, 0x18, 0xd4, 0x30, 0x0c, 0xa1, 0x6d, 0xc8, 0xe9, 0x25, 0x76, 0x9a, 0xcf, 0x44,
	0x1b, 0xef, 0xa2, 0x61, 0x23, 0xdd, 0x84, 0xcf, 0x62, 0x0d, 0x6e, 0xee, 0xc7, 0x83, 0x78, 0xff,
	0xd3, 0xae, 0x2c, 0xf0, 0x5d, 0x56, 0x1e, 0x89, 0x7f, 0x5a, 0x4c, 0xfa, 0xf4, 0xa6, 0x34, 0xa8,
	0xf7, 0xd4, 0x78, 0x7c, 0x49, 0x91, 0xd6, 0x4a, 0x35, 0x22, 0x6d, 0x51, 0xb8, 0x05, 0x37, 0xb4,
	0xca, 0x71, 0x47, 0x56, 0xd9, 0x64, 0x58, 0x1e, 0x2a, 0xb6, 0xd6, 0xcc, 0x5c, 0xa2, 0x72, 0x4c,
	0xe6, 0x65, 0xc2, 0x67, 0xd0, 0xe5, 0x42, 0x20, 0xf9, 0xc5, 0x4c, 0x53, 0xdd, 0x24, 0x9e, 0x1d,
	0x7e, 0x05, 0x1d, 0x8a, 0x76, 0x15, 0xb5, 0xaf, 0xaa, 0x08, 0xcb, 0xa3, 0xf0, 0x8d, 0xa5, 0x31,
	0x39, 0x0e, 0x53, 0x4e, 0x51, 0x27, 0xf1, 0x98, 0x78, 0x46, 0x56, 0x27, 0x9c, 0xf4, 0x65, 0xcb,
	0xab, 0x31, 0xc5, 0xee, 0x0c, 0x75, 0x95, 0xa9, 0x32, 0x5a, 0xe1, 0xa8, 0xd7, 0x30, 0x8c, 0x61,
	0x45, 0x6a, 0xad, 0xce, 0x51, 0x47, 0x5d, 0xbe, 0x50, 0xe4, 0x0d, 0xbf, 0xd5, 0x88, 0x23, 0x95,
	0xa7, 0x19, 0xea, 0xd7, 0xd2, 0xc8, 0xa4, 0x16, 0x0c, 0xbf, 0x86, 0xe5, 0x54, 0xaa, 0x74, 0x5a,
	0x46, 0xbd, 0x2f, 0x7c, 0xe2, 0xe4, 0xc2, 0x4d, 0xe8, 0x54, 0xa7, 0x28, 0x75, 0x04, 0x5f, 0xf8,
	0xc0, 0x8a, 0x91, 0xfc, 0xa1, 0xac, 0x8e, 0xb3, 0xa8, 0xff, 0x25, 0x79, 0x16, 0x0b, 0x9f, 0xc0,
	0x32, 0x17, 0x43, 0x15, 0xad, 0x72, 0xf4, 0x6e, 0xfa, 0x0f, 0xb8, 0x76, 0x12, 0xc7, 0x15, 0xaf,
	0xe0, 0x0e, 0xa5, 0x3b, 0xc1, 0x43, 0x8d, 0xd5, 0x71, 0xa2, 0x54, 0x41, 0x15, 0x4d, 0x69, 0xd2,
	0xee, 0x1c, 0x05, 0x0b, 0xe1, 0x27, 0xa1, 0xc4, 0xb3, 0xc5, 0x9f, 0x01, 0xac, 0x92, 0x8a, 0x1f,
	0x54, 0x56, 0x12, 0x2b, 0x7c, 0x0e, 0xcb, 0x05, 0x16, 0x63, 0xd4, 0x5c, 0x2f, 0xfd, 0xf8, 0xce,
	0xdc, 0x97, 0xfb, 0xcc, 0x4a, 0x9c, 0x48, 0xa3, 0xb8, 0x96, 0xe6, 0x8a, 0xeb, 0x1b, 0xe8, 0xd3,
	0x69, 0x84, 0xc6, 0x64, 0xe5, 0x11, 0x17, 0x6d, 0x3f, 0x5e, 0x9f, 0xd3, 0xe4, 0x78, 0x49, 0x53,
	0x50, 0xfc, 0x1e, 0x40, 0xbf, 0xc1, 0xa4, 0x27, 0x54, 0xc8, 0x53, 0x5f, 0xbb, 0x16, 0xf0, 0xc3,
	0xae, 0x3e, 0x4a, 0xfd, 0x56, 0x9d, 0xb3, 0xdd, 0x6e, 0xe2, 0x31, 0xf1, 0x8e, 0x64, 0x81, 0xef,
	0x2f, 0x4f, 0xb1, 0x6e, 0x15, 0x35, 0x0e, 0x37, 0xe0, 0xd6, 0xf8, 0xa7, 0xa9, 0xa9, 0xb2, 0x14,
	0xf7, 0x55, 0x59, 0x19, 0xd4, 0xfc, 0x34, 0xbb, 0xc9, 0x22, 0x59, 0xbc, 0x82, 0x35, 0x1b, 0x57,
	0x99, 0x5e, 0x8e, 0xa6, 0x93, 0x09, 0x56, 0x95, 0xbd, 0x2b, 0x57, 0x6a, 0xc0, 0xef, 0xd2, 0x21,
	0xf2, 0x51, 0x93, 0x9c, 0x73, 0xc5, 0x02, 0xf1, 0xc6, 0x66, 0x66, 0x64, 0xa4, 0x36, 0x3b, 0x5c,
	0xd2, 0x7b, 0x4a, 0xb2, 0xeb, 0x32, 0xcf, 0x59, 0x2f, 0xab, 0xe9, 0x26, 0x1e, 0xd3, 0x13, 0xaf,
	0xa8, 0xd8, 0x6d, 0x28, 0xf9, 0x2c, 0x6e, 0xc3, 0xad, 0x05, 0x35, 0xe2, 0x83, 0x25, 0x59, 0xf4,
	0x56, 0x53, 0xa7, 0x79, 0x08, 0x70, 0x48, 0x87, 0x81, 0x9a, 0x96, 0xc6, 0xc5, 0xaa, 0x41, 0x09,
	0x05, 0xb4, 0x26, 0x05, 0x29, 0xa6, 0x52, 0x58, 0xf3, 0x69, 0x18, 0xa8, 0xa2, 0x90, 0x65, 0x9a,
	0x10, 0x53, 0x6c, 0xd8, 0xce, 0x41, 0xd1, 0x7f, 0x8d, 0x39, 0x1a, 0xbc, 0xae, 0x73, 0x88, 0x1d,
	0x17, 0x1c, 0x95, 0xe3, 0xcf, 0xd3, 0xcc, 0x70, 0xd5, 0x5c, 0x17, 0x9c, 0x6b, 0x0a, 0x44, 0xfc,
	0x1d, 0x58, 0x25, 0xf6, 0x16, 0x09, 0x56, 0xd3, 0xdc, 0x90, 0xb0, 0x3c, 0x97, 0x3a, 0x7d, 0x51,
	0x1b, 0xb4, 0xc8, 0xd3, 0xe3, 0x5a, 0x89, 0x45, 0x9e, 0xbe, 0xe5, 0x32, 0xed, 0x10, 0x0f, 0x17,
	0x9a, 0x1b, 0x2f, 0x5c, 0xe7, 0x75, 0xc8, 0xd3, 0x63, 0xd7, 0x6b, 0x1c, 0xf2, 0xf4, 0x2d, 0xd7,
	0x67, 0x1c, 0xf2, 0x09, 0x59, 0x99, 0x25, 0x84, 0x3a, 0x4f, 0xa9, 0xce, 0x79, 0xa6, 0x74, 0xf9,
	0xa6, 0x35, 0x14, 0x25, 0x84, 0x74, 0xa3, 0x8f, 0xd2, 0x4c, 0x8e, 0xb7, 0xd3, 0xca, 0xdd, 0x69,
	0x1d, 0x3a, 0x63, 0x75, 0x31, 0xab, 0x60, 0x06, 0x57, 0xa5, 0x7a, 0x36, 0xfa, 0x5a, 0xcd, 0xd1,
	0xd7, 0xb0, 0xd7, 0x9e, 0xb7, 0xf7, 0xd2, 0xda, 0x1b, 0x1c, 0xcb, 0xf2, 0x08, 0x0f, 0xea, 0xa1,
	0xf3, 0x10, 0x40, 0xb3, 0x65, 0x1e, 0x49, 0x01, 0x37, 0xc7, 0x06, 0x45, 0xc4, 0xb0, 0x3e, 0xfb,
	0x6a, 0xfb, 0x4c, 0x1a, 0xa9, 0x87, 0x13, 0x55, 0x72, 0x61, 0x5a, 0x54, 0xbb, 0xea, 0xb1, 0x78,
	0x6a, 0x6b, 0xd9, 0x7e, 0x33, 0xc2, 0x0b, 0x77, 0xb5, 0x35, 0x68, 0x55, 0x78, 0xe1, 0xa4, 0xe9,
	0x28, 0x5e, 0x36, 0x95, 0x8f, 0xb2, 0xa3, 0xd2, 0x49, 0x3e, 0x80, 0x1e, 0x6a, 0xad, 0xf4, 0x40,
	0xa5, 0xe8, 0xe4, 0x67, 0x04, 0xf1, 0x57, 0x50, 0x77, 0x31, 0x5b, 0x0d, 0x03, 0x55, 0x96, 0x38,
	0xf1, 0x5d, 0x8c, 0x87, 0x4d, 0xf0, 0xd9, 0x70, 0xaa, 0xbb, 0x18, 0x0f, 0x9b, 0x97, 0xd0, 0x9d,
	0xd8, 0x62, 0xae, 0x5c, 0x95, 0xcf, 0x5a, 0xec, 0x48, 0x9e, 0xa1, 0xab, 0x74, 0xea, 0x78, 0x89,
	0x97, 0xf4, 0x59, 0x68, 0x35, 0xb2, 0x30, 0xff, 0x94, 0xda, 0x8b, 0x4f, 0x49, 0x7c, 0x07, 0xb7,
	0xad, 0xaf, 0xe4, 0xc1, 0xff, 0xf7, 0x54, 0x7c, 0x84, 0x5b, 0x0b, 0x0e, 0x79, 0x93, 0x43, 0xce,
	0x7e, 0xf3, 0xf5, 0x32, 0x25, 0x7c, 0x0c, 0xed, 0x49, 0xe1, 0x2f, 0xf6, 0xf9, 0xf3, 0x65, 0xae,
	0xf8, 0xd1, 0x3a, 0xb6, 0x33, 0xbd, 0xe4, 0x41, 0xec, 0x5f, 0xd4, 0x95, 0x6b, 0x9c, 0xaf, 0x12,
	0xce, 0x88, 0xad, 0xc2, 0x06, 0x45, 0x1c, 0xdb, 0x44, 0xee, 0xa1, 0xd4, 0xe5, 0xe8, 0x24, 0xa3,
	0x0e, 0xc5, 0xfa, 0x22, 0x58, 0xa9, 0x08, 0xce, 0x76, 0x16, 0x07, 0x1b, 0x96, 0x96, 0x16, 0x2d,
	0xb1, 0xc8, 0x3b, 0x95, 0x95, 0xc6, 0x45, 0xba, 0x41, 0x11, 0x87, 0x70, 0x97, 0x2c, 0xed, 0xa2,
	0xd9, 0x51, 0x17, 0xdb, 0xf4, 0x7e, 0x9d, 0xa9, 0x67, 0x76, 0x7b, 0xbb, 0x72, 0x86, 0xf1, 0x0a,
	0xe1, 0xd9, 0xa1, 0x80, 0x55, 0x7a, 0x56, 0xb4, 0x41, 0x36, 0x76, 0xc7, 0x39, 0x9a, 0xf8, 0xc5,
	0xbe, 0x96, 0x5d, 0x34, 0x76, 0x82, 0xfa, 0xfb, 0x5c, 0xb3, 0x83, 0x3d, 0x87, 0x1e, 0x77, 0x13,
	0xd2, 0xe0, 0x22, 0xbf, 0x60, 0x7f, 0xc6, 0x17, 0x07, 0x56, 0xf9, 0x08, 0xf3, 0x9c, 0x59, 0xbe,
	0xea, 0x33, 0xef, 0x93, 0xab, 0x7a, 0x4f, 0xa0, 0x07, 0x47, 0x3d, 0x72, 0x57, 0xe5, 0x75, 0xc8,
	0x3c, 0x16, 0x5b, 0xd0, 0x27, 0x7d, 0xdb, 0x69, 0x4a, 0xce, 0x86, 0x8f, 0xa1, 0xc3, 0x6e, 0xb9,
	0xda, 0x5a, 0x5c, 0x06, 0x2c, 0x53, 0x4c, 0x6c, 0x01, 0x7c, 0xa8, 0xf0, 0x3f, 0xfb, 0x30, 0xdb,
	0xc2, 0x97, 0xe6, 0xb6, 0xf0, 0xc6, 0x4e, 0xdd, 0x9a, 0xdb, 0xa9, 0xc5, 0x13, 0x3b, 0x25, 0x78,
	0x1e, 0xbd, 0x93, 0xd3, 0x8a, 0xb7, 0xdc, 0x53, 0x3a, 0xb8, 0x71, 0x66, 0x81, 0xf8, 0x2d, 0xb0,
	0x21, 0xa9, 0x97, 0x6c, 0xe7, 0x4e, 0x0c, 0x5d, 0xda, 0x9d, 0x79, 0x3a, 0x93, 0xfc, 0xcd, 0xf8,
	0xde, 0xec, 0x32, 0xb5, 0x2c, 0x71, 0x13, 0x2f, 0x17, 0x7e, 0x0b, 0xab, 0xba, 0xb1, 0xaa, 0xbb,
	0x64, 0xdc, 0x9d, 0x3d, 0xb0, 0x06, 0x33, 0x99, 0x13, 0x1d, 0x2f, 0xf3, 0x4f, 0xcd, 0xd6, 0xbf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xf0, 0xf0, 0x7b, 0x00, 0x0d, 0x00, 0x00,
}
