// Code generated by protoc-gen-go. DO NOT EDIT.
// source: M2G.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type M2G_RegisterGate struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2G_RegisterGate) Reset()         { *m = M2G_RegisterGate{} }
func (m *M2G_RegisterGate) String() string { return proto.CompactTextString(m) }
func (*M2G_RegisterGate) ProtoMessage()    {}
func (*M2G_RegisterGate) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2G_a687539d792e67ce, []int{0}
}
func (m *M2G_RegisterGate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2G_RegisterGate.Unmarshal(m, b)
}
func (m *M2G_RegisterGate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2G_RegisterGate.Marshal(b, m, deterministic)
}
func (dst *M2G_RegisterGate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2G_RegisterGate.Merge(dst, src)
}
func (m *M2G_RegisterGate) XXX_Size() int {
	return xxx_messageInfo_M2G_RegisterGate.Size(m)
}
func (m *M2G_RegisterGate) XXX_DiscardUnknown() {
	xxx_messageInfo_M2G_RegisterGate.DiscardUnknown(m)
}

var xxx_messageInfo_M2G_RegisterGate proto.InternalMessageInfo

func (m *M2G_RegisterGate) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type M2G_LoginSuccessNotifyGate struct {
	ServerId             int32    `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	RoleId               int64    `protobuf:"varint,2,opt,name=roleId,proto3" json:"roleId,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2G_LoginSuccessNotifyGate) Reset()         { *m = M2G_LoginSuccessNotifyGate{} }
func (m *M2G_LoginSuccessNotifyGate) String() string { return proto.CompactTextString(m) }
func (*M2G_LoginSuccessNotifyGate) ProtoMessage()    {}
func (*M2G_LoginSuccessNotifyGate) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2G_a687539d792e67ce, []int{1}
}
func (m *M2G_LoginSuccessNotifyGate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2G_LoginSuccessNotifyGate.Unmarshal(m, b)
}
func (m *M2G_LoginSuccessNotifyGate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2G_LoginSuccessNotifyGate.Marshal(b, m, deterministic)
}
func (dst *M2G_LoginSuccessNotifyGate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2G_LoginSuccessNotifyGate.Merge(dst, src)
}
func (m *M2G_LoginSuccessNotifyGate) XXX_Size() int {
	return xxx_messageInfo_M2G_LoginSuccessNotifyGate.Size(m)
}
func (m *M2G_LoginSuccessNotifyGate) XXX_DiscardUnknown() {
	xxx_messageInfo_M2G_LoginSuccessNotifyGate.DiscardUnknown(m)
}

var xxx_messageInfo_M2G_LoginSuccessNotifyGate proto.InternalMessageInfo

func (m *M2G_LoginSuccessNotifyGate) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *M2G_LoginSuccessNotifyGate) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *M2G_LoginSuccessNotifyGate) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*M2G_RegisterGate)(nil), "message.M2G_RegisterGate")
	proto.RegisterType((*M2G_LoginSuccessNotifyGate)(nil), "message.M2G_LoginSuccessNotifyGate")
}

func init() { proto.RegisterFile("M2G.proto", fileDescriptor_M2G_a687539d792e67ce) }

var fileDescriptor_M2G_a687539d792e67ce = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xf4, 0x35, 0x72, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55, 0x52,
	0xe2, 0x12, 0xf0, 0x35, 0x72, 0x8f, 0x0f, 0x4a, 0x4d, 0xcf, 0x2c, 0x2e, 0x49, 0x2d, 0x72, 0x4f,
	0x2c, 0x49, 0x15, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62,
	0xca, 0x4c, 0x51, 0xca, 0xe0, 0x92, 0x02, 0xa9, 0xf1, 0xc9, 0x4f, 0xcf, 0xcc, 0x0b, 0x2e, 0x4d,
	0x4e, 0x4e, 0x2d, 0x2e, 0xf6, 0xcb, 0x2f, 0xc9, 0x4c, 0xab, 0x04, 0xab, 0x96, 0xe2, 0xe2, 0x28,
	0x4e, 0x2d, 0x2a, 0x4b, 0x2d, 0xf2, 0x84, 0xe9, 0x81, 0xf3, 0x85, 0xc4, 0xb8, 0xd8, 0x8a, 0xf2,
	0x73, 0x52, 0x3d, 0x53, 0x24, 0x98, 0x14, 0x18, 0x35, 0x98, 0x83, 0xa0, 0x3c, 0x90, 0x78, 0x69,
	0x31, 0x58, 0x07, 0x33, 0x44, 0x1c, 0xc2, 0x4b, 0x62, 0x03, 0xbb, 0xce, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0x37, 0x8e, 0xe0, 0x12, 0xaa, 0x00, 0x00, 0x00,
}
