// Code generated by protoc-gen-go. DO NOT EDIT.
// source: M2G.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type M2G_RegisterGate struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2G_RegisterGate) Reset()         { *m = M2G_RegisterGate{} }
func (m *M2G_RegisterGate) String() string { return proto.CompactTextString(m) }
func (*M2G_RegisterGate) ProtoMessage()    {}
func (*M2G_RegisterGate) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2G_8c950aa142d725a2, []int{0}
}
func (m *M2G_RegisterGate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2G_RegisterGate.Unmarshal(m, b)
}
func (m *M2G_RegisterGate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2G_RegisterGate.Marshal(b, m, deterministic)
}
func (dst *M2G_RegisterGate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2G_RegisterGate.Merge(dst, src)
}
func (m *M2G_RegisterGate) XXX_Size() int {
	return xxx_messageInfo_M2G_RegisterGate.Size(m)
}
func (m *M2G_RegisterGate) XXX_DiscardUnknown() {
	xxx_messageInfo_M2G_RegisterGate.DiscardUnknown(m)
}

var xxx_messageInfo_M2G_RegisterGate proto.InternalMessageInfo

func (m *M2G_RegisterGate) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type M2G_LoginSuccessNotifyGate struct {
	ServerId             int32    `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	RoleId               int64    `protobuf:"varint,2,opt,name=roleId,proto3" json:"roleId,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	NeedClose            bool     `protobuf:"varint,4,opt,name=needClose,proto3" json:"needClose,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2G_LoginSuccessNotifyGate) Reset()         { *m = M2G_LoginSuccessNotifyGate{} }
func (m *M2G_LoginSuccessNotifyGate) String() string { return proto.CompactTextString(m) }
func (*M2G_LoginSuccessNotifyGate) ProtoMessage()    {}
func (*M2G_LoginSuccessNotifyGate) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2G_8c950aa142d725a2, []int{1}
}
func (m *M2G_LoginSuccessNotifyGate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2G_LoginSuccessNotifyGate.Unmarshal(m, b)
}
func (m *M2G_LoginSuccessNotifyGate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2G_LoginSuccessNotifyGate.Marshal(b, m, deterministic)
}
func (dst *M2G_LoginSuccessNotifyGate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2G_LoginSuccessNotifyGate.Merge(dst, src)
}
func (m *M2G_LoginSuccessNotifyGate) XXX_Size() int {
	return xxx_messageInfo_M2G_LoginSuccessNotifyGate.Size(m)
}
func (m *M2G_LoginSuccessNotifyGate) XXX_DiscardUnknown() {
	xxx_messageInfo_M2G_LoginSuccessNotifyGate.DiscardUnknown(m)
}

var xxx_messageInfo_M2G_LoginSuccessNotifyGate proto.InternalMessageInfo

func (m *M2G_LoginSuccessNotifyGate) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *M2G_LoginSuccessNotifyGate) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *M2G_LoginSuccessNotifyGate) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *M2G_LoginSuccessNotifyGate) GetNeedClose() bool {
	if m != nil {
		return m.NeedClose
	}
	return false
}

type M2G_RoleQuitGate struct {
	RoleId               int64    `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2G_RoleQuitGate) Reset()         { *m = M2G_RoleQuitGate{} }
func (m *M2G_RoleQuitGate) String() string { return proto.CompactTextString(m) }
func (*M2G_RoleQuitGate) ProtoMessage()    {}
func (*M2G_RoleQuitGate) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2G_8c950aa142d725a2, []int{2}
}
func (m *M2G_RoleQuitGate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2G_RoleQuitGate.Unmarshal(m, b)
}
func (m *M2G_RoleQuitGate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2G_RoleQuitGate.Marshal(b, m, deterministic)
}
func (dst *M2G_RoleQuitGate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2G_RoleQuitGate.Merge(dst, src)
}
func (m *M2G_RoleQuitGate) XXX_Size() int {
	return xxx_messageInfo_M2G_RoleQuitGate.Size(m)
}
func (m *M2G_RoleQuitGate) XXX_DiscardUnknown() {
	xxx_messageInfo_M2G_RoleQuitGate.DiscardUnknown(m)
}

var xxx_messageInfo_M2G_RoleQuitGate proto.InternalMessageInfo

func (m *M2G_RoleQuitGate) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

type M2G_BindZhangHao struct {
	ZhangHaoType         ZhangHaoType `protobuf:"varint,1,opt,name=zhangHaoType,proto3,enum=message.ZhangHaoType" json:"zhangHaoType,omitempty"`
	Value                string       `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	UserId               int64        `protobuf:"varint,3,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *M2G_BindZhangHao) Reset()         { *m = M2G_BindZhangHao{} }
func (m *M2G_BindZhangHao) String() string { return proto.CompactTextString(m) }
func (*M2G_BindZhangHao) ProtoMessage()    {}
func (*M2G_BindZhangHao) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2G_8c950aa142d725a2, []int{3}
}
func (m *M2G_BindZhangHao) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2G_BindZhangHao.Unmarshal(m, b)
}
func (m *M2G_BindZhangHao) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2G_BindZhangHao.Marshal(b, m, deterministic)
}
func (dst *M2G_BindZhangHao) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2G_BindZhangHao.Merge(dst, src)
}
func (m *M2G_BindZhangHao) XXX_Size() int {
	return xxx_messageInfo_M2G_BindZhangHao.Size(m)
}
func (m *M2G_BindZhangHao) XXX_DiscardUnknown() {
	xxx_messageInfo_M2G_BindZhangHao.DiscardUnknown(m)
}

var xxx_messageInfo_M2G_BindZhangHao proto.InternalMessageInfo

func (m *M2G_BindZhangHao) GetZhangHaoType() ZhangHaoType {
	if m != nil {
		return m.ZhangHaoType
	}
	return ZhangHaoType_QQ
}

func (m *M2G_BindZhangHao) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *M2G_BindZhangHao) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

// 关闭session
type M2G_CloseSession struct {
	RoleId               int64    `protobuf:"varint,1,opt,name=roleId,proto3" json:"roleId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2G_CloseSession) Reset()         { *m = M2G_CloseSession{} }
func (m *M2G_CloseSession) String() string { return proto.CompactTextString(m) }
func (*M2G_CloseSession) ProtoMessage()    {}
func (*M2G_CloseSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_M2G_8c950aa142d725a2, []int{4}
}
func (m *M2G_CloseSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2G_CloseSession.Unmarshal(m, b)
}
func (m *M2G_CloseSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2G_CloseSession.Marshal(b, m, deterministic)
}
func (dst *M2G_CloseSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2G_CloseSession.Merge(dst, src)
}
func (m *M2G_CloseSession) XXX_Size() int {
	return xxx_messageInfo_M2G_CloseSession.Size(m)
}
func (m *M2G_CloseSession) XXX_DiscardUnknown() {
	xxx_messageInfo_M2G_CloseSession.DiscardUnknown(m)
}

var xxx_messageInfo_M2G_CloseSession proto.InternalMessageInfo

func (m *M2G_CloseSession) GetRoleId() int64 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func init() {
	proto.RegisterType((*M2G_RegisterGate)(nil), "message.M2G_RegisterGate")
	proto.RegisterType((*M2G_LoginSuccessNotifyGate)(nil), "message.M2G_LoginSuccessNotifyGate")
	proto.RegisterType((*M2G_RoleQuitGate)(nil), "message.M2G_RoleQuitGate")
	proto.RegisterType((*M2G_BindZhangHao)(nil), "message.M2G_BindZhangHao")
	proto.RegisterType((*M2G_CloseSession)(nil), "message.M2G_CloseSession")
}

func init() { proto.RegisterFile("M2G.proto", fileDescriptor_M2G_8c950aa142d725a2) }

var fileDescriptor_M2G_8c950aa142d725a2 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x25, 0x9d, 0x9b, 0x6b, 0x90, 0x21, 0x41, 0xa5, 0x14, 0x0f, 0xa5, 0xa7, 0xe2, 0xa1, 0x87,
	0x7a, 0xf2, 0xea, 0x0e, 0x75, 0x60, 0x05, 0x33, 0x4f, 0xbb, 0x48, 0x5d, 0x3e, 0x6b, 0xa0, 0x26,
	0x23, 0x5f, 0x3a, 0x98, 0xde, 0xfd, 0xdd, 0xb2, 0xa4, 0x73, 0xf3, 0xb0, 0x5b, 0xde, 0xcb, 0x7b,
	0xbc, 0xf7, 0x12, 0x1a, 0x56, 0x45, 0x99, 0xaf, 0x8c, 0xb6, 0x9a, 0x9d, 0x7e, 0x02, 0x62, 0xdd,
	0x40, 0x1c, 0x4e, 0x8b, 0xca, 0x73, 0x69, 0x4a, 0xcf, 0xab, 0xa2, 0x7c, 0xe5, 0xd0, 0x48, 0xb4,
	0x60, 0xca, 0xda, 0x02, 0x9b, 0xd0, 0x40, 0x8a, 0x88, 0x24, 0x24, 0x1b, 0xf2, 0x40, 0x8a, 0xf4,
	0x87, 0xd0, 0x78, 0x2b, 0x7a, 0xd4, 0x8d, 0x54, 0xf3, 0x6e, 0xb9, 0x04, 0xc4, 0x27, 0x6d, 0xe5,
	0xfb, 0xc6, 0xc9, 0x63, 0x3a, 0x46, 0x30, 0x6b, 0x30, 0xb3, 0x9d, 0xe9, 0x0f, 0xb3, 0x2b, 0x3a,
	0x32, 0xba, 0x85, 0x99, 0x88, 0x82, 0x84, 0x64, 0x03, 0xde, 0xa3, 0x2d, 0xdf, 0xa1, 0x73, 0x0c,
	0x3c, 0xef, 0x11, 0xbb, 0xa6, 0xa1, 0x02, 0x10, 0xd3, 0x56, 0x23, 0x44, 0x27, 0x09, 0xc9, 0xc6,
	0x7c, 0x4f, 0xa4, 0x37, 0x7d, 0x59, 0xdd, 0xc2, 0x73, 0x27, 0xad, 0x4b, 0xdf, 0x27, 0x90, 0xc3,
	0x84, 0xf4, 0xdb, 0x6b, 0xef, 0xa5, 0x12, 0x8b, 0x8f, 0x5a, 0x35, 0x0f, 0xb5, 0x66, 0x77, 0xf4,
	0xec, 0xab, 0x3f, 0xbf, 0x6c, 0x56, 0xe0, 0x1c, 0x93, 0xe2, 0x32, 0xef, 0xdf, 0x25, 0x5f, 0x1c,
	0x5c, 0xf2, 0x7f, 0x52, 0x76, 0x41, 0x87, 0xeb, 0xba, 0xed, 0xc0, 0xed, 0x08, 0xb9, 0x07, 0xc7,
	0x66, 0xec, 0x8a, 0xba, 0xd6, 0x73, 0x40, 0x94, 0x5a, 0x1d, 0x2b, 0xfa, 0x36, 0x72, 0x1f, 0x71,
	0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x33, 0x79, 0x21, 0xf8, 0xa9, 0x01, 0x00, 0x00,
}
